r"""Fused certified Gaussian/Haar copula for Jacobi level coupling.

This module is additive to the immutable Jacobi CUDA implementation.  It
reuses that implementation's header-free double-double ball arithmetic and
certified exponential, then adds a rigorously enclosed normal CDF/inverse and
the orthogonal Haar recursion.  CUDA ``normcdfinv`` is used only to propose a
small root bracket; interval Newton steps and strict endpoint tests authorize
the result.

The normal CDF is evaluated locally about quarter-integer anchors.  Anchor
values are generated by the pinned Arb backend, split into double-double
centres plus outward radii, and embedded in the NVRTC source.  On a local
coordinate ``|d| <= 1/8`` the entire exponential-integral series is summed
through degree 56.  A frozen ``2^-120`` remainder is conservative for
``|anchor| <= 38`` (the analytic majorant is below ``2^-127``).  Any lane
outside the proved domain is unresolved and must use the transition-local Arb
fallback owned by the higher-level coupling API.

The Gaussian variables produced here are a copula only.  They are never used
as a transition or state approximation.
"""

from __future__ import annotations

import ctypes
from dataclasses import dataclass
from fractions import Fraction
import functools
import hashlib
import json
import math
from pathlib import Path
import threading
import time
from typing import Any, Mapping

try:
    import torch
    from torch import Tensor
except ImportError:  # pragma: no cover
    torch = None
    Tensor = Any

try:
    import flint
    from flint import arb
    from flint import ctx as flint_ctx
except ImportError:  # pragma: no cover
    flint = None
    arb = None
    flint_ctx = None

from mnist import d0_jacobi_rb_cuda_fused as _jacobi_fused
from mnist.d0_jacobi_rb_cuda_certificate import (
    dd_from_fraction,
    fraction_to_float_up,
)


HAAR_FUSED_CUDA_VERSION = "d0-jacobi-rb-haar-normal-dd-quarter-anchor-v1"
HAAR_FUSED_KERNEL_NAME = "jacobi_rb_haar_normal_authorize_v1"
HAAR_NORMAL_PREFIX_KERNEL_NAME = "jacobi_rb_haar_normal_prefix_authorize_v1"
HAAR_UNIFORM_FUSED_KERNEL_NAME = "jacobi_rb_haar_uniform_authorize_v1"
HAAR_UNIFORM_PREFIX_KERNEL_NAME = "jacobi_rb_haar_uniform_prefix_v1"
HAAR_FUSED_SELFTEST_NAME = "jacobi_rb_haar_normal_selftest_v1"
HAAR_FUSED_COMPILE_FLAGS = (
    "--std=c++17",
    "--fmad=false",
    "--ftz=false",
    "--prec-div=true",
    "--prec-sqrt=true",
)
HAAR_NORMAL_SOURCE_BITS = 128
HAAR_NORMAL_MAX_SOURCES = 5
HAAR_NORMAL_ANCHOR_QUARTERS = 152
HAAR_NORMAL_SERIES_DEGREE = 56
HAAR_NORMAL_SERIES_REMAINDER_HEX = "0x1.0p-120"
HAAR_NORMAL_REQUIRED_SELFTEST_MASK = (1 << 5) - 1
_U64_MASK = (1 << 64) - 1
_CACHE: dict[tuple[int, int, int, str], "HaarFusedBundle"] = {}
_LOCK = threading.Lock()


class HaarFusedCudaError(RuntimeError):
    """The fused authorizer could not establish its runtime contract."""


def _cuda_driver_api_version() -> int | None:
    """Read the CUDA driver API version without requiring a toolkit."""

    candidates = (
        ("nvcuda.dll", getattr(ctypes, "WinDLL", ctypes.CDLL))
        if hasattr(ctypes, "WinDLL")
        else ("libcuda.so.1", ctypes.CDLL)
    )
    try:
        library = candidates[1](candidates[0])
        value = ctypes.c_int()
        status = int(library.cuDriverGetVersion(ctypes.byref(value)))
        return int(value.value) if status == 0 else None
    except (OSError, AttributeError, TypeError, ValueError):
        return None


@dataclass(frozen=True)
class HaarFusedBundle:
    normal_authorizer: Any
    normal_prefix_authorizer: Any
    uniform_authorizer: Any
    prefix_proposal: Any
    selftest_mask: int
    binary_sha256: str
    source_sha256: str
    constants_sha256: str


@dataclass(frozen=True)
class HaarFusedLaunch:
    normal_center_hi: Tensor
    normal_center_lo: Tensor
    normal_radius: Tensor
    normal_lower: Tensor
    normal_upper: Tensor
    uniform_center_hi: Tensor
    uniform_center_lo: Tensor
    uniform_radius: Tensor
    uniform_lower: Tensor
    uniform_upper: Tensor
    certificate_mask: Tensor
    fallback_reason_codes: Tensor
    prefix_bits: Tensor
    elapsed_seconds: float
    bundle: HaarFusedBundle


@dataclass(frozen=True)
class HaarUniformFusedLaunch:
    later: Tensor
    target: Tensor
    quantile_lower: Tensor
    quantile_upper: Tensor
    target_lower: Tensor
    target_upper: Tensor
    modes_used: Tensor
    certificate_codes: Tensor
    authorized_mask: Tensor
    fallback_reason_codes: Tensor
    candidate: Tensor
    launch_count: int
    elapsed_seconds: float
    bundle: HaarFusedBundle


def _canonical_bytes(value: Any) -> bytes:
    if isinstance(value, bytes):
        return b"bytes:" + value
    if isinstance(value, str):
        return b"str:" + value.encode("utf-8")
    try:
        encoded = json.dumps(
            value, sort_keys=True, separators=(",", ":"), allow_nan=False
        )
    except (TypeError, ValueError) as exc:
        raise TypeError(
            "identifier material must be bytes, text, or canonical JSON"
        ) from exc
    return b"json:" + encoded.encode("utf-8")


def canonical_haar_seed(value: Any) -> int:
    """Match the immutable Jacobi Philox key convention without private calls."""

    if isinstance(value, int) and not isinstance(value, bool):
        if not 0 <= value <= _U64_MASK:
            raise ValueError("root_seed must lie in uint64 range")
    digest = hashlib.sha256(
        b"d0-jacobi-rb-philox-key-v2\0" + _canonical_bytes(value)
    ).digest()
    return int.from_bytes(digest[:8], "little", signed=False)


def _exact_arb_integer(value: Any) -> int:
    if not bool(value.is_exact()):
        raise HaarFusedCudaError("Arb endpoint conversion was not exact")
    mantissa, exponent = value.man_exp()
    integer, power = int(mantissa), int(exponent)
    if power >= 0:
        return integer << power
    denominator = 1 << (-power)
    if integer % denominator:
        raise HaarFusedCudaError("Arb endpoint was not an exact dyadic integer")
    return integer // denominator


def _arb_fraction_bounds(value: Any, bits: int = 220) -> tuple[Fraction, Fraction]:
    scale = arb(2) ** int(bits)
    lower = _exact_arb_integer((value.lower() * scale).floor())
    upper = _exact_arb_integer((value.upper() * scale).ceil())
    denominator = 1 << int(bits)
    return Fraction(lower, denominator), Fraction(upper, denominator)


def _dd_ball_hex(lower: Fraction, upper: Fraction) -> tuple[str, str, str]:
    midpoint = (lower + upper) / 2
    centre = dd_from_fraction(midpoint)
    exact_centre = centre.exact
    radius = max(exact_centre - lower, upper - exact_centre, Fraction(0))
    outward = fraction_to_float_up(radius)
    return centre.hi.hex(), centre.lo.hex(), outward.hex()


@functools.lru_cache(maxsize=1)
def _normal_constants() -> tuple[tuple[tuple[str, str, str], ...], str]:
    if (
        arb is None
        or flint_ctx is None
        or flint is None
        or str(getattr(flint, "__version__", "")) != "0.9.0"
    ):
        raise HaarFusedCudaError(
            "python-flint==0.9.0 is required to freeze normal constants"
        )
    previous = int(flint_ctx.prec)
    rows: list[tuple[str, str, str]] = []
    try:
        flint_ctx.prec = 384
        sqrt_two = arb(2).sqrt()
        sqrt_two_pi = (2 * arb.pi()).sqrt()
        for quarter in range(
            -HAAR_NORMAL_ANCHOR_QUARTERS,
            HAAR_NORMAL_ANCHOR_QUARTERS + 1,
        ):
            anchor = arb(quarter) / 4
            density = (-anchor * anchor / 2).exp() / sqrt_two_pi
            cdf = (1 + (anchor / sqrt_two).erf()) / 2
            rows.append(_dd_ball_hex(*_arb_fraction_bounds(cdf)))
            rows.append(_dd_ball_hex(*_arb_fraction_bounds(density)))
        inv_sqrt_two = 1 / sqrt_two
        inv_sqrt_two_pi = 1 / sqrt_two_pi
        rows.append(_dd_ball_hex(*_arb_fraction_bounds(inv_sqrt_two)))
        rows.append(_dd_ball_hex(*_arb_fraction_bounds(inv_sqrt_two_pi)))
    finally:
        flint_ctx.prec = previous
    payload = "|".join(item for row in rows for item in row)
    return tuple(rows), hashlib.sha256(payload.encode("ascii")).hexdigest()


def _constant_array(
    name: str, rows: tuple[tuple[str, str, str], ...], offset: int, stride: int
) -> str:
    selected = rows[offset : 2 * (2 * HAAR_NORMAL_ANCHOR_QUARTERS + 1) : stride]
    return "\n".join(
        (
            f"__device__ __constant__ double {name}_HI[{len(selected)}] = {{"
            + ",".join(row[0] for row in selected)
            + "};",
            f"__device__ __constant__ double {name}_LO[{len(selected)}] = {{"
            + ",".join(row[1] for row in selected)
            + "};",
            f"__device__ __constant__ double {name}_RAD[{len(selected)}] = {{"
            + ",".join(row[2] for row in selected)
            + "};",
        )
    )


_HAAR_KERNEL = r"""
__device__ __forceinline__ Ball haar_anchor(
    const double* hi, const double* lo, const double* radius, int index
) {
    Ball out={{hi[index],lo[index]},radius[index],1};
    out.ok=finite_d(out.c.hi)&&finite_d(out.c.lo)&&finite_d(out.r)&&out.r>=0.0;
    return out;
}

__device__ __forceinline__ Ball haar_inv_sqrt_two() {
    Ball out={{HAAR_INV_SQRT_TWO_HI,HAAR_INV_SQRT_TWO_LO},
              HAAR_INV_SQRT_TWO_RAD,1};
    return out;
}
__device__ __forceinline__ Ball haar_inv_sqrt_two_pi() {
    Ball out={{HAAR_INV_SQRT_TWO_PI_HI,HAAR_INV_SQRT_TWO_PI_LO},
              HAAR_INV_SQRT_TWO_PI_RAD,1};
    return out;
}

// Integral identity:
// Phi(a+d)=Phi(a)+phi(a)*integral_0^d exp(-a*t-t*t/2)dt.
// Coefficients obey c_n=-(a*c_(n-1)+c_(n-2))/n.  For |a|<=38,
// |d|<=1/8, the degree-56 integral remainder is <2^-127.
__device__ __forceinline__ Ball haar_normal_cdf(Ball z) {
    if (!z.ok) return invalid_ball();
    double midpoint=dd_rn(z.c);
    if (!finite_d(midpoint)||midpoint<-38.0||midpoint>38.0) return invalid_ball();
    int quarter=__double2int_rn(__dmul_rn(midpoint,4.0));
    if (quarter<-152||quarter>152) return invalid_ball();
    int index=quarter+152;
    double anchor=__dmul_rn((double)quarter,0.25);
    Ball delta=ball_sub(z,exact_double(anchor));
    if (!delta.ok||ball_lower(delta)<-0.1250000000001||
        ball_upper(delta)>0.1250000000001) return invalid_ball();
    Ball cdf_anchor=haar_anchor(
        HAAR_PHI_HI,HAAR_PHI_LO,HAAR_PHI_RAD,index);
    Ball density_anchor=haar_anchor(
        HAAR_PDF_HI,HAAR_PDF_LO,HAAR_PDF_RAD,index);
    Ball c_nm2=exact_double(1.0);
    Ball c_nm1=exact_double(-anchor);
    Ball power=delta;
    Ball integral=delta;
    power=ball_mul(power,delta);
    integral=ball_add(
        integral,
        ball_div(ball_mul(c_nm1,power),exact_double(2.0)));
    for (int n=2;n<=56;++n) {
        Ball numerator=ball_neg(
            ball_add(ball_scale(c_nm1,anchor),c_nm2));
        Ball coefficient=ball_div(numerator,exact_double((double)n));
        power=ball_mul(power,delta);
        integral=ball_add(
            integral,
            ball_div(
                ball_mul(coefficient,power),
                exact_double((double)(n+1))));
        c_nm2=c_nm1;
        c_nm1=coefficient;
        if (!integral.ok) return invalid_ball();
    }
    integral=ball_expand(integral,HAAR_SERIES_REMAINDER);
    Ball result=ball_add(cdf_anchor,ball_mul(density_anchor,integral));
    if (!result.ok||ball_lower(result)<0.0||ball_upper(result)>1.0)
        return invalid_ball();
    return result;
}

__device__ __forceinline__ Ball haar_normal_pdf_range(Ball z) {
    if (!z.ok) return invalid_ball();
    double lo=ball_lower(z),hi=ball_upper(z);
    if (!finite_d(lo)||!finite_d(hi)||lo>hi) return invalid_ball();
    double maxabs=dmax(dabs(lo),dabs(hi));
    double minabs=(lo<=0.0&&hi>=0.0)?0.0:dmin(dabs(lo),dabs(hi));
    double maxsq=__dmul_ru(maxabs,maxabs);
    double minsq=__dmul_rd(minabs,minabs);
    double exponent_lo=__dmul_rd(-0.5,maxsq);
    double exponent_hi=__dmul_ru(-0.5,minsq);
    Ball exponential=exp24(ball_from_bounds(exponent_lo,exponent_hi));
    return ball_mul(exponential,haar_inv_sqrt_two_pi());
}

__device__ __forceinline__ Ball haar_inverse_normal(Ball probability) {
    if (!probability.ok||!(ball_lower(probability)>0.0)||
        !(ball_upper(probability)<1.0)) return invalid_ball();
    Ball target=probability;
    double midpoint=0.0;
    int upper_tail=ball_lower(probability)>0.5;
    if (upper_tail) {
        // DD probability centres can retain a tail far below one binary64
        // ulp at one.  Form 1-p as a ball before rounding the proposal input.
        target=ball_sub(exact_double(1.0),probability);
    }
    midpoint=dd_rn(target.c);
    if (!(midpoint>0.0&&midpoint<1.0)) return invalid_ball();
    // Proposal only.  The strict endpoint tests below authorize the bracket.
    double proposal=normcdfinv(midpoint);
    if (!finite_d(proposal)||proposal<=-38.0||proposal>=38.0)
        return invalid_ball();
    Ball bracket=invalid_ball();
    double radius=1.0e-7;
    for (int attempt=0;attempt<6;++attempt) {
        double lo=__dsub_rd(proposal,radius);
        double hi=__dadd_ru(proposal,radius);
        Ball flo=haar_normal_cdf(exact_double(lo));
        Ball fhi=haar_normal_cdf(exact_double(hi));
        if (flo.ok&&fhi.ok&&
            ball_upper(flo)<ball_lower(target)&&
            ball_lower(fhi)>ball_upper(target)) {
            bracket=ball_from_bounds(lo,hi);
            break;
        }
        radius=__dmul_ru(radius,10.0);
    }
    if (!bracket.ok) return invalid_ball();
    // Interval Newton.  The derivative ball encloses phi on the entire
    // current bracket, so the next ball contains every root in that bracket.
    for (int iteration=0;iteration<7;++iteration) {
        Ball midpoint_ball=exact_dd(bracket.c);
        Ball cdf=haar_normal_cdf(midpoint_ball);
        Ball derivative=haar_normal_pdf_range(bracket);
        Ball correction=ball_div(ball_sub(target,cdf),derivative);
        Ball next=ball_add(midpoint_ball,correction);
        if (!next.ok||ball_lower(next)<ball_lower(bracket)||
            ball_upper(next)>ball_upper(bracket)) return invalid_ball();
        bracket=next;
    }
    return upper_tail?ball_neg(bracket):bracket;
}

extern "C" __global__ void jacobi_rb_haar_normal_authorize_v1(
    const u64* source_ids, const int* depths, const int* branch_codes,
    const int* detail_signs, const u64* seed_pointer, int count,
    int source_stride, double* normal_center_hi, double* normal_center_lo,
    double* normal_radius, double* normal_lower, double* normal_upper,
    double* uniform_center_hi, double* uniform_center_lo,
    double* uniform_radius, double* uniform_lower, double* uniform_upper,
    u8* certified, u8* reasons, int* prefix_bits
) {
    int index=(int)(blockIdx.x*blockDim.x+threadIdx.x);
    if (index>=count) return;
    normal_center_hi[index]=0.0; normal_center_lo[index]=0.0;
    normal_radius[index]=0.0; normal_lower[index]=0.0; normal_upper[index]=0.0;
    uniform_center_hi[index]=0.5; uniform_center_lo[index]=0.0;
    uniform_radius[index]=0.5;
    uniform_lower[index]=0.0; uniform_upper[index]=1.0;
    certified[index]=0; reasons[index]=0; prefix_bits[index]=0;
    int depth=depths[index];
    if (depth<0||depth>=source_stride||source_stride>5) { reasons[index]=1; return; }
    Ball node=invalid_ball();
    for (int source=0;source<=depth;++source) {
        u64 source_id=source_ids[index*source_stride+source];
        u64 first=philox_word(seed_pointer[0],source_id,0);
        u64 second=philox_word(seed_pointer[0],source_id,1);
        if ((first==0ULL&&second==0ULL)||
            (first==0xffffffffffffffffULL&&second==0xffffffffffffffffULL)) {
            reasons[index]=2; return;
        }
        Ball source_probability_lo=dyadic128(first,second,0);
        Ball source_probability_hi=dyadic128(first,second,1);
        // Preserve the 128-bit dyadic information in the DD centre.  Turning
        // the two endpoints into ordinary doubles here would widen almost
        // every source cell to one binary64 ulp before the Haar recursion.
        Ball source_span=ball_sub(source_probability_hi,source_probability_lo);
        if (!source_span.ok) { reasons[index]=3; return; }
        Ball source_probability=source_probability_lo;
        source_probability.r=__dadd_ru(
            source_probability.r,
            dmax(0.0,ball_upper(source_span)));
        source_probability.ok=finite_d(source_probability.r);
        Ball gaussian=haar_inverse_normal(source_probability);
        if (!gaussian.ok) { reasons[index]=3; return; }
        if (source==0) {
            node=gaussian;
        } else {
            int bit=(branch_codes[index]>>(depth-source))&1;
            int sign=bit? -1:1;
            sign*=detail_signs[index];
            node=ball_mul(
                ball_add(node,ball_scale(gaussian,(double)sign)),
                haar_inv_sqrt_two());
            if (!node.ok) { reasons[index]=4; return; }
        }
    }
    Ball uniform=haar_normal_cdf(node);
    if (!uniform.ok||!(ball_lower(uniform)>0.0)||
        !(ball_upper(uniform)<1.0)) { reasons[index]=5; return; }
    normal_center_hi[index]=node.c.hi; normal_center_lo[index]=node.c.lo;
    normal_radius[index]=node.r;
    normal_lower[index]=ball_lower(node); normal_upper[index]=ball_upper(node);
    uniform_center_hi[index]=uniform.c.hi;
    uniform_center_lo[index]=uniform.c.lo;
    uniform_radius[index]=uniform.r;
    uniform_lower[index]=ball_lower(uniform);
    uniform_upper[index]=ball_upper(uniform);
    certified[index]=1; reasons[index]=0; prefix_bits[index]=128;
}

// Deterministic injected-prefix entry point used by the authorizing extreme
// normal-transform preflight.  It executes the same inverse/CDF proof as the
// production source-ID kernel but does not depend on finding a rare Philox
// realization.
extern "C" __global__ void jacobi_rb_haar_normal_prefix_authorize_v1(
    const u64* prefix_hi,const u64* prefix_lo,int count,
    double* normal_center_hi,double* normal_center_lo,
    double* normal_radius,double* normal_lower,double* normal_upper,
    double* uniform_center_hi,double* uniform_center_lo,
    double* uniform_radius,double* uniform_lower,double* uniform_upper,
    u8* certified,u8* reasons,int* prefix_bits
) {
    int index=(int)(blockIdx.x*blockDim.x+threadIdx.x);
    if (index>=count) return;
    normal_center_hi[index]=0.0; normal_center_lo[index]=0.0;
    normal_radius[index]=0.0; normal_lower[index]=0.0; normal_upper[index]=0.0;
    uniform_center_hi[index]=0.5; uniform_center_lo[index]=0.0;
    uniform_radius[index]=0.5;
    uniform_lower[index]=0.0; uniform_upper[index]=1.0;
    certified[index]=0; reasons[index]=0; prefix_bits[index]=0;
    u64 first=prefix_hi[index],second=prefix_lo[index];
    if ((first==0ULL&&second==0ULL)||
        (first==0xffffffffffffffffULL&&second==0xffffffffffffffffULL)) {
        reasons[index]=2; return;
    }
    Ball source_lo=dyadic128(first,second,0);
    Ball source_hi=dyadic128(first,second,1);
    Ball span=ball_sub(source_hi,source_lo);
    if (!span.ok) { reasons[index]=3; return; }
    Ball probability=source_lo;
    probability.r=__dadd_ru(
        probability.r,dmax(0.0,ball_upper(span)));
    probability.ok=finite_d(probability.r);
    Ball normal=haar_inverse_normal(probability);
    if (!normal.ok) { reasons[index]=3; return; }
    Ball uniform=haar_normal_cdf(normal);
    if (!uniform.ok||!(ball_lower(uniform)>0.0)||
        !(ball_upper(uniform)<1.0)) { reasons[index]=5; return; }
    normal_center_hi[index]=normal.c.hi;
    normal_center_lo[index]=normal.c.lo;
    normal_radius[index]=normal.r;
    normal_lower[index]=ball_lower(normal);
    normal_upper[index]=ball_upper(normal);
    uniform_center_hi[index]=uniform.c.hi;
    uniform_center_lo[index]=uniform.c.lo;
    uniform_radius[index]=uniform.r;
    uniform_lower[index]=ball_lower(uniform);
    uniform_upper[index]=ball_upper(uniform);
    certified[index]=1; reasons[index]=0; prefix_bits[index]=128;
}

// Strict Jacobi authorization from an arbitrary certified uniform interval.
// The binary64 lower/upper inputs are outward endpoints; no midpoint or
// enclosing dyadic cell participates in the proof.
extern "C" __global__ void jacobi_rb_haar_uniform_authorize_v1(
    const double* x, const double* exposure, const double* uniform_lower_input,
    const double* uniform_upper_input, const double* uniform_center_hi_input,
    const double* uniform_center_lo_input, const double* uniform_radius_input,
    const double* proposed_y, int count, int mode_cap,
    double* later, double* target, double* quantile_lower,
    double* quantile_upper, double* target_lower, double* target_upper,
    int* modes_used, u8* certificate_codes, u8* authorized, u8* reasons
) {
    int index=(int)(blockIdx.x*blockDim.x+threadIdx.x);
    if (index>=count) return;
    double xv=x[index],uv=exposure[index],yv=proposed_y[index];
    double ulo=uniform_lower_input[index],uhi=uniform_upper_input[index];
    later[index]=xv; target[index]=0.0;
    quantile_lower[index]=xv; quantile_upper[index]=xv;
    target_lower[index]=0.0; target_upper[index]=0.0;
    modes_used[index]=0; certificate_codes[index]=0;
    authorized[index]=0; reasons[index]=0;
    if (uv==0.0) { authorized[index]=1; certificate_codes[index]=15; return; }
    if (!finite_d(xv)||!finite_d(uv)||!finite_d(yv)||
        !finite_d(ulo)||!finite_d(uhi)||xv<0.0||xv>1.0||uv<=0.0||
        yv<=0.0||yv>=1.0||!(ulo>0.0)||!(uhi<1.0)||!(ulo<uhi)||
        mode_cap<128||mode_cap>8192) { reasons[index]=6; return; }
    Ball ycell_lo,ycell_hi;
    if (!rounding_boundaries(yv,&ycell_lo,&ycell_hi)) {
        reasons[index]=11; return;
    }
    Ball xball=exact_double(xv),uball=exact_double(uv),yball=exact_double(yv);
    Ball zx=exact_affine_coordinate(xball);
    Ball zylo=exact_affine_coordinate(ycell_lo);
    Ball zyhi=exact_affine_coordinate(ycell_hi);
    Ball zyt=exact_affine_coordinate(yball);
    Ball px_prev=exact_double(1.0),px_cur=zx;
    double px_maximum_legendre_local_error=0.0;
    SpectralState slo=state_init(ycell_lo,zylo,0);
    SpectralState shi=state_init(ycell_hi,zyhi,0);
    SpectralState st=state_init(yball,zyt,1);
    Ball uniform_cell={{
        uniform_center_hi_input[index],uniform_center_lo_input[index]},
        uniform_radius_input[index],1};
    // The DD ball must enclose the complete outward endpoint interval.
    // Merely lying inside [ulo,uhi] would be unsound: it could authorize a
    // strict subset while excluding the latent uniform.
    if (!uniform_cell.ok||ball_lower(uniform_cell)>ulo||
        ball_upper(uniform_cell)<uhi||!(ball_lower(uniform_cell)>0.0)||
        !(ball_upper(uniform_cell)<1.0)) { reasons[index]=6; return; }
    // try_certificate consumes a lower and upper endpoint ball.  The same
    // complete cell is admissible in both positions: strict comparisons use
    // its upper endpoint on the left test and its lower endpoint on the right
    // test through ball_strict_less.
    Ball uniform_lo=uniform_cell,uniform_hi=uniform_cell;
    Ball qbase=exp24(ball_scale(uball,-2.0));
    Ball qpower=qbase,decay=qbase;
    if (!qbase.ok) { reasons[index]=4; return; }
    int last_reason=8,last_mode=1;
    for (int n=1;n<mode_cap;++n) {
        last_mode=n+1;
        Ball lo_next=legendre_next(
            slo.previous,slo.current,zylo,n,
            &slo.maximum_legendre_local_error);
        Ball hi_next=legendre_next(
            shi.previous,shi.current,zyhi,n,
            &shi.maximum_legendre_local_error);
        Ball t_next=legendre_next(
            st.previous,st.current,zyt,n,
            &st.maximum_legendre_local_error);
        if (!lo_next.ok) { last_reason=12; break; }
        if (!hi_next.ok) { last_reason=13; break; }
        if (!t_next.ok) { last_reason=14; break; }
        if (!decay.ok) { last_reason=15; break; }
        Ball coefficient=ball_scale(decay,(double)(2*n+1));
        slo.cdf=ball_add(
            slo.cdf,
            ball_scale(
                ball_mul(ball_mul(decay,px_cur),
                         ball_sub(lo_next,slo.previous)),0.5));
        shi.cdf=ball_add(
            shi.cdf,
            ball_scale(
                ball_mul(ball_mul(decay,px_cur),
                         ball_sub(hi_next,shi.previous)),0.5));
        st.cdf=ball_add(
            st.cdf,
            ball_scale(
                ball_mul(ball_mul(decay,px_cur),
                         ball_sub(t_next,st.previous)),0.5));
        st.density=ball_add(
            st.density,ball_mul(ball_mul(coefficient,px_cur),st.current));
        Ball basis=ball_scale(
            ball_sub(st.previous,ball_mul(zyt,st.current)),
            __dmul_rn(0.5,(double)n));
        st.conormal=ball_add(
            st.conormal,ball_mul(ball_mul(coefficient,px_cur),basis));
        Ball px_next=legendre_next(
            px_prev,px_cur,zx,n,&px_maximum_legendre_local_error);
        if (!slo.cdf.ok||!shi.cdf.ok||!st.cdf.ok||!st.density.ok||
            !basis.ok||!st.conormal.ok||!px_next.ok) {
            last_reason=7; break;
        }
        slo.previous=slo.current; slo.current=lo_next;
        shi.previous=shi.current; shi.current=hi_next;
        st.previous=st.current; st.current=t_next;
        px_prev=px_cur; px_cur=px_next;
        int m=n+1;
        qpower=ball_mul(qpower,qbase);
        decay=ball_mul(decay,qpower);
        int bucket=(m>=128&&(m%16)==0)||m==mode_cap;
        if (!bucket) continue;
        Tail tail=tail_bounds_from_powers(m,decay,qpower);
        double zvalue=0.0,zlo=0.0,zhi=0.0;
        if (try_certificate(
                slo.cdf,shi.cdf,st.density,st.conormal,tail,
                uniform_lo,uniform_hi,&zvalue,&zlo,&zhi,&last_reason)) {
            later[index]=yv; target[index]=zvalue;
            quantile_lower[index]=dd_down(ycell_lo.c);
            quantile_upper[index]=dd_up(ycell_hi.c);
            target_lower[index]=zlo; target_upper[index]=zhi;
            modes_used[index]=m; certificate_codes[index]=15;
            authorized[index]=1; reasons[index]=0; return;
        }
        if (tail.ok&&tail.cdf<0x1.0p-79) {
            Ball full_cdf=ball_expand(st.cdf,tail.cdf);
            Ball full_density=ball_expand(st.density,tail.density);
            if (full_cdf.ok&&full_density.ok&&ball_lower(full_density)>0.0) {
                Ball uniform_mid=ball_scale(
                    ball_add(uniform_lo,uniform_hi),0.5);
                Ball delta=ball_div(
                    ball_sub(uniform_mid,full_cdf),full_density);
                Ball repaired=ball_add(yball,delta);
                double repair_value=dd_rn(repaired.c);
                if (repaired.ok&&finite_d(repair_value)&&
                    repair_value>0.0&&repair_value<1.0)
                    later[index]=repair_value;
            }
        }
    }
    modes_used[index]=last_mode;
    reasons[index]=(u8)(last_reason?last_reason:8);
}

extern "C" __global__ void jacobi_rb_haar_uniform_prefix_v1(
    const double* uniform_lower_input,const double* uniform_upper_input,
    int count,u64* numerators,int* bits
) {
    int index=(int)(blockIdx.x*blockDim.x+threadIdx.x);
    if (index>=count) return;
    double midpoint=__dadd_rn(
        uniform_lower_input[index],
        __dmul_rn(
            __dsub_rn(uniform_upper_input[index],uniform_lower_input[index]),
            0.5));
    if (!(midpoint>0.0&&midpoint<1.0)) {
        numerators[index]=0ULL; bits[index]=1; return;
    }
    double scaled=__dmul_rn(midpoint,0x1.0p+64);
    if (scaled>=0x1.0p+64) {
        numerators[index]=0xffffffffffffffffULL;
    } else {
        numerators[index]=__double2ull_rd(scaled);
    }
    bits[index]=64;
}

extern "C" __global__ void jacobi_rb_haar_normal_selftest_v1(u64* result) {
    if (blockIdx.x||threadIdx.x) return;
    u64 mask=0;
    Ball zero=exact_double(0.0);
    Ball half=haar_normal_cdf(zero);
    if (half.ok&&ball_lower(half)<=0.5&&ball_upper(half)>=0.5) mask|=1ULL;
    Ball p=ball_from_bounds(0.4999999999999999,0.5000000000000001);
    Ball inverse=haar_inverse_normal(p);
    if (inverse.ok&&ball_lower(inverse)<0.0&&ball_upper(inverse)>0.0) mask|=2ULL;
    Ball parent=exact_double(0.75),detail=exact_double(-0.25);
    Ball left=ball_mul(ball_add(parent,detail),haar_inv_sqrt_two());
    Ball right=ball_mul(ball_sub(parent,detail),haar_inv_sqrt_two());
    Ball recovered=ball_mul(ball_add(left,right),haar_inv_sqrt_two());
    if (recovered.ok&&ball_lower(recovered)<=0.75&&ball_upper(recovered)>=0.75)
        mask|=4ULL;
    Ball density=haar_normal_pdf_range(exact_double(1.0));
    if (density.ok&&ball_lower(density)>0.0) mask|=8ULL;
    if (HAAR_SERIES_REMAINDER>=0x1.0p-127) mask|=16ULL;
    result[0]=mask;
}
"""


@functools.lru_cache(maxsize=1)
def _cuda_source() -> tuple[str, str, str]:
    rows, constants_sha = _normal_constants()
    anchor_count = 2 * HAAR_NORMAL_ANCHOR_QUARTERS + 1
    phi = rows[: 2 * anchor_count : 2]
    pdf = rows[1 : 2 * anchor_count : 2]
    inv_sqrt_two = rows[-2]
    inv_sqrt_two_pi = rows[-1]

    def arrays(name: str, values: tuple[tuple[str, str, str], ...]) -> str:
        return "\n".join(
            (
                f"__device__ __constant__ double {name}_HI[{len(values)}]={{"
                + ",".join(row[0] for row in values)
                + "};",
                f"__device__ __constant__ double {name}_LO[{len(values)}]={{"
                + ",".join(row[1] for row in values)
                + "};",
                f"__device__ __constant__ double {name}_RAD[{len(values)}]={{"
                + ",".join(row[2] for row in values)
                + "};",
            )
        )

    constants = "\n".join(
        (
            arrays("HAAR_PHI", phi),
            arrays("HAAR_PDF", pdf),
            f"#define HAAR_INV_SQRT_TWO_HI ({inv_sqrt_two[0]})",
            f"#define HAAR_INV_SQRT_TWO_LO ({inv_sqrt_two[1]})",
            f"#define HAAR_INV_SQRT_TWO_RAD ({inv_sqrt_two[2]})",
            f"#define HAAR_INV_SQRT_TWO_PI_HI ({inv_sqrt_two_pi[0]})",
            f"#define HAAR_INV_SQRT_TWO_PI_LO ({inv_sqrt_two_pi[1]})",
            f"#define HAAR_INV_SQRT_TWO_PI_RAD ({inv_sqrt_two_pi[2]})",
            f"#define HAAR_SERIES_REMAINDER ({HAAR_NORMAL_SERIES_REMAINDER_HEX})",
        )
    )
    source = _jacobi_fused._CUDA_SOURCE + "\n" + constants + "\n" + _HAAR_KERNEL
    return source, hashlib.sha256(source.encode("utf-8")).hexdigest(), constants_sha


def verify_normal_constants() -> dict[str, Any]:
    """Recompute every frozen enclosure with Arb and verify source binding."""

    try:
        rows, constants_sha = _normal_constants()
        source, source_sha, observed_constants_sha = _cuda_source()
    except Exception as exc:
        return {
            "passed": 0,
            "error": f"{type(exc).__name__}: {exc}",
            "version": HAAR_FUSED_CUDA_VERSION,
        }
    errors: list[str] = []
    if constants_sha != observed_constants_sha:
        errors.append("constant fingerprint")
    if len(rows) != 2 * (2 * HAAR_NORMAL_ANCHOR_QUARTERS + 1) + 2:
        errors.append("constant count")
    for row in rows:
        if any(value not in source for value in row):
            errors.append("source binding")
            break
    # Analytic tail majorant at |a*d|=4.75 and d^2/2=1/128.
    majorant = [1.0, 4.75]
    for degree in range(2, 130):
        majorant.append(
            (4.75 * majorant[-1] + (1.0 / 64.0) * majorant[-2]) / degree
        )
    tail = 0.125 * (
        sum(majorant[HAAR_NORMAL_SERIES_DEGREE + 1 : 129])
        + majorant[129] / 0.9
    )
    if tail > float.fromhex(HAAR_NORMAL_SERIES_REMAINDER_HEX):
        errors.append("series remainder")
    return {
        "passed": int(not errors),
        "version": HAAR_FUSED_CUDA_VERSION,
        "source_sha256": source_sha,
        "constants_sha256": constants_sha,
        "anchor_count": 2 * HAAR_NORMAL_ANCHOR_QUARTERS + 1,
        "series_degree": HAAR_NORMAL_SERIES_DEGREE,
        "series_remainder_hex": HAAR_NORMAL_SERIES_REMAINDER_HEX,
        "analytic_tail_bound": tail,
        "errors": errors,
    }


def _compile(device: Any) -> HaarFusedBundle:
    if torch is None or not torch.cuda.is_available():
        raise HaarFusedCudaError("CUDA is unavailable")
    report = verify_normal_constants()
    if not report.get("passed"):
        raise HaarFusedCudaError(f"normal constant preflight failed: {report}")
    index = torch.device(device).index
    if index is None:
        index = int(torch.cuda.current_device())
    props = torch.cuda.get_device_properties(index)
    source, source_sha, constants_sha = _cuda_source()
    key = (index, int(props.major), int(props.minor), source_sha)
    with _LOCK:
        cached = _CACHE.get(key)
        if cached is not None:
            return cached
        from torch.cuda._utils import _cuda_load_module, _nvrtc_compile
        from torch.utils import cpp_extension

        previous_cuda_home = cpp_extension.CUDA_HOME
        if previous_cuda_home is None:
            cpp_extension.CUDA_HOME = str(Path(torch.__file__).resolve().parent)
        try:
            with torch.cuda.device(index):
                binary, lowered = _nvrtc_compile(
                    source,
                    HAAR_FUSED_KERNEL_NAME,
                    compute_capability=f"{props.major}{props.minor}",
                    nvcc_options=list(HAAR_FUSED_COMPILE_FLAGS),
                )
                loaded = _cuda_load_module(
                    binary,
                    [
                        lowered,
                        HAAR_NORMAL_PREFIX_KERNEL_NAME,
                        HAAR_UNIFORM_FUSED_KERNEL_NAME,
                        HAAR_UNIFORM_PREFIX_KERNEL_NAME,
                        HAAR_FUSED_SELFTEST_NAME,
                    ],
                )
                selftest = torch.zeros(1, dtype=torch.uint64, device=device)
                loaded[HAAR_FUSED_SELFTEST_NAME](
                    grid=(1, 1, 1),
                    block=(1, 1, 1),
                    args=[selftest],
                    stream=torch.cuda.current_stream(device),
                )
                torch.cuda.synchronize(device)
                observed = int(selftest.item())
                if observed != HAAR_NORMAL_REQUIRED_SELFTEST_MASK:
                    raise HaarFusedCudaError(
                        "normal CUDA self-test failed: "
                        f"observed=0x{observed:x}, "
                        f"required=0x{HAAR_NORMAL_REQUIRED_SELFTEST_MASK:x}"
                    )
                bundle = HaarFusedBundle(
                    normal_authorizer=loaded[lowered],
                    normal_prefix_authorizer=loaded[
                        HAAR_NORMAL_PREFIX_KERNEL_NAME
                    ],
                    uniform_authorizer=loaded[HAAR_UNIFORM_FUSED_KERNEL_NAME],
                    prefix_proposal=loaded[HAAR_UNIFORM_PREFIX_KERNEL_NAME],
                    selftest_mask=observed,
                    binary_sha256=hashlib.sha256(binary).hexdigest(),
                    source_sha256=source_sha,
                    constants_sha256=constants_sha,
                )
        finally:
            cpp_extension.CUDA_HOME = previous_cuda_home
        _CACHE[key] = bundle
        return bundle


def launch_certified_haar_normal_transform(
    source_ids: Tensor,
    depths: Tensor,
    branch_codes: Tensor,
    detail_signs: Tensor,
    *,
    root_seed: Any,
    threads_per_block: int = 128,
) -> HaarFusedLaunch:
    """Authorize one Gaussian/Haar-derived uniform enclosure per CUDA lane."""

    if torch is None:
        raise HaarFusedCudaError("PyTorch is unavailable")
    if not isinstance(source_ids, torch.Tensor) or not source_ids.is_cuda:
        raise TypeError("source_ids must be a CUDA tensor")
    if source_ids.dtype != torch.uint64 or source_ids.ndim != 2:
        raise TypeError("source_ids must have shape [N,S] and dtype uint64")
    if not source_ids.is_contiguous():
        raise ValueError("source_ids must be contiguous")
    count, stride = map(int, source_ids.shape)
    if not 1 <= stride <= HAAR_NORMAL_MAX_SOURCES:
        raise ValueError("source_ids has an unsupported source stride")
    for name, tensor in (
        ("depths", depths),
        ("branch_codes", branch_codes),
        ("detail_signs", detail_signs),
    ):
        if not isinstance(tensor, torch.Tensor) or not tensor.is_cuda:
            raise TypeError(f"{name} must be a CUDA tensor")
        if tensor.dtype != torch.int32 or tensor.shape != (count,):
            raise TypeError(f"{name} must be contiguous int32 with shape [N]")
        if not tensor.is_contiguous() or tensor.device != source_ids.device:
            raise ValueError(f"{name} must share source_ids device and contiguity")
    if count > 4096:
        raise ValueError("Haar CUDA launches are capped at 4096 lanes")
    if int(threads_per_block) not in {32, 64, 128, 256, 512}:
        raise ValueError("threads_per_block must be a supported whole-warp size")
    if bool(((depths < 0) | (depths >= stride)).any()):
        raise ValueError("depths must lie in [0, source stride)")
    if bool((branch_codes < 0).any()):
        raise ValueError("branch_codes must be nonnegative")
    if bool(((detail_signs != -1) & (detail_signs != 1)).any()):
        raise ValueError("detail_signs must contain only -1 or +1")
    bundle = _compile(source_ids.device)
    normal_center_hi = torch.empty(
        count, dtype=torch.float64, device=source_ids.device
    )
    normal_center_lo = torch.empty_like(normal_center_hi)
    normal_radius = torch.empty_like(normal_center_hi)
    normal_lower = torch.empty(count, dtype=torch.float64, device=source_ids.device)
    normal_upper = torch.empty_like(normal_lower)
    uniform_center_hi = torch.empty_like(normal_lower)
    uniform_center_lo = torch.empty_like(normal_lower)
    uniform_radius = torch.empty_like(normal_lower)
    uniform_lower = torch.empty_like(normal_lower)
    uniform_upper = torch.empty_like(normal_lower)
    certificate = torch.zeros(count, dtype=torch.uint8, device=source_ids.device)
    reasons = torch.zeros_like(certificate)
    prefix_bits = torch.zeros(count, dtype=torch.int32, device=source_ids.device)
    seed = torch.tensor(
        [canonical_haar_seed(root_seed)], dtype=torch.uint64, device=source_ids.device
    )
    blocks = (count + int(threads_per_block) - 1) // int(threads_per_block)
    started = time.perf_counter()
    bundle.normal_authorizer(
        grid=(blocks, 1, 1),
        block=(int(threads_per_block), 1, 1),
        args=[
            source_ids,
            depths,
            branch_codes,
            detail_signs,
            seed,
            count,
            stride,
            normal_center_hi,
            normal_center_lo,
            normal_radius,
            normal_lower,
            normal_upper,
            uniform_center_hi,
            uniform_center_lo,
            uniform_radius,
            uniform_lower,
            uniform_upper,
            certificate,
            reasons,
            prefix_bits,
        ],
        stream=torch.cuda.current_stream(source_ids.device),
    )
    torch.cuda.synchronize(source_ids.device)
    elapsed = time.perf_counter() - started
    return HaarFusedLaunch(
        normal_center_hi=normal_center_hi,
        normal_center_lo=normal_center_lo,
        normal_radius=normal_radius,
        normal_lower=normal_lower,
        normal_upper=normal_upper,
        uniform_center_hi=uniform_center_hi,
        uniform_center_lo=uniform_center_lo,
        uniform_radius=uniform_radius,
        uniform_lower=uniform_lower,
        uniform_upper=uniform_upper,
        certificate_mask=certificate.bool(),
        fallback_reason_codes=reasons,
        prefix_bits=prefix_bits,
        elapsed_seconds=elapsed,
        bundle=bundle,
    )


def launch_certified_normal_prefix_transform(
    prefix_hi: Tensor,
    prefix_lo: Tensor,
    *,
    threads_per_block: int = 128,
) -> HaarFusedLaunch:
    """Authorize injected 128-bit dyadic prefixes with the fused CUDA proof."""

    if torch is None:
        raise HaarFusedCudaError("PyTorch is unavailable")
    for name, value in (("prefix_hi", prefix_hi), ("prefix_lo", prefix_lo)):
        if (
            not isinstance(value, torch.Tensor)
            or not value.is_cuda
            or value.dtype != torch.uint64
            or value.ndim != 1
            or not value.is_contiguous()
        ):
            raise TypeError(f"{name} must be contiguous CUDA uint64 [N]")
    if prefix_hi.shape != prefix_lo.shape or prefix_hi.device != prefix_lo.device:
        raise ValueError("prefix words must share shape and CUDA device")
    count = int(prefix_hi.numel())
    if not 1 <= count <= 4096:
        raise ValueError("prefix launch count must lie in [1,4096]")
    if int(threads_per_block) not in {32, 64, 128, 256, 512}:
        raise ValueError("threads_per_block must be a supported whole-warp size")
    bundle = _compile(prefix_hi.device)
    outputs = [
        torch.empty(count, dtype=torch.float64, device=prefix_hi.device)
        for _ in range(10)
    ]
    (
        normal_center_hi,
        normal_center_lo,
        normal_radius,
        normal_lower,
        normal_upper,
        uniform_center_hi,
        uniform_center_lo,
        uniform_radius,
        uniform_lower,
        uniform_upper,
    ) = outputs
    certificate = torch.zeros(count, dtype=torch.uint8, device=prefix_hi.device)
    reasons = torch.zeros_like(certificate)
    prefix_bits = torch.zeros(count, dtype=torch.int32, device=prefix_hi.device)
    blocks = (count + int(threads_per_block) - 1) // int(threads_per_block)
    started = time.perf_counter()
    bundle.normal_prefix_authorizer(
        grid=(blocks, 1, 1),
        block=(int(threads_per_block), 1, 1),
        args=[
            prefix_hi,
            prefix_lo,
            count,
            *outputs,
            certificate,
            reasons,
            prefix_bits,
        ],
        stream=torch.cuda.current_stream(prefix_hi.device),
    )
    torch.cuda.synchronize(prefix_hi.device)
    return HaarFusedLaunch(
        normal_center_hi=normal_center_hi,
        normal_center_lo=normal_center_lo,
        normal_radius=normal_radius,
        normal_lower=normal_lower,
        normal_upper=normal_upper,
        uniform_center_hi=uniform_center_hi,
        uniform_center_lo=uniform_center_lo,
        uniform_radius=uniform_radius,
        uniform_lower=uniform_lower,
        uniform_upper=uniform_upper,
        certificate_mask=certificate.bool(),
        fallback_reason_codes=reasons,
        prefix_bits=prefix_bits,
        elapsed_seconds=time.perf_counter() - started,
        bundle=bundle,
    )


def _launch_jacobi_candidate_from_uniform_midpoint(
    bundle: HaarFusedBundle,
    head_fraction: Tensor,
    exposure: Tensor,
    uniform_lower: Tensor,
    uniform_upper: Tensor,
    transition_ids: Tensor,
    *,
    threads_per_block: int,
) -> Tensor:
    """Run the immutable nonauthorizing Jacobi proposal at a 64-bit midpoint."""

    # This is a deliberately narrow compatibility shim around the immutable
    # candidate kernel.  Its output is never authorizing; the new arbitrary-
    # interval kernel below proves every accepted rounding cell.
    from mnist import d0_jacobi_rb_cuda as rb_cuda

    count = int(head_fraction.numel())
    device = head_fraction.device
    numerators = torch.empty(count, dtype=torch.uint64, device=device)
    bits = torch.empty(count, dtype=torch.int32, device=device)
    blocks = (count + int(threads_per_block) - 1) // int(threads_per_block)
    bundle.prefix_proposal(
        grid=(blocks, 1, 1),
        block=(int(threads_per_block), 1, 1),
        args=[
            uniform_lower,
            uniform_upper,
            count,
            numerators,
            bits,
        ],
        stream=torch.cuda.current_stream(device),
    )
    profile = rb_cuda.JacobiRBCudaProfile(
        threads_per_block=int(threads_per_block)
    )
    candidate_kernel, _binary_sha = rb_cuda._load_cuda_kernel(device, profile)
    candidate = torch.empty_like(head_fraction)
    target_scratch = torch.empty_like(head_fraction)
    lower_scratch = torch.empty_like(head_fraction)
    upper_scratch = torch.empty_like(head_fraction)
    candidate_kernel(
        grid=(blocks, 1, 1),
        block=(int(threads_per_block), 1, 1),
        args=[
            head_fraction,
            exposure,
            transition_ids,
            torch.zeros(1, dtype=torch.uint64, device=device),
            numerators,
            bits,
            1,
            count,
            int(profile.candidate_modes),
            int(profile.candidate_bisection_steps),
            candidate,
            target_scratch,
            lower_scratch,
            upper_scratch,
        ],
        stream=torch.cuda.current_stream(device),
    )
    return candidate


def launch_certified_jacobi_from_uniform_cells(
    head_fraction: Tensor,
    exposure: Tensor,
    uniform_lower: Tensor,
    uniform_upper: Tensor,
    transition_ids: Tensor,
    *,
    uniform_center_hi: Tensor | None = None,
    uniform_center_lo: Tensor | None = None,
    uniform_radius: Tensor | None = None,
    threads_per_block: int = 128,
    mode_cap: int = 8192,
) -> HaarUniformFusedLaunch:
    """Strictly authorize Jacobi quantile/target cells from arbitrary U cells."""

    if torch is None:
        raise HaarFusedCudaError("PyTorch is unavailable")
    tensors = (
        ("head_fraction", head_fraction, torch.float64),
        ("exposure", exposure, torch.float64),
        ("uniform_lower", uniform_lower, torch.float64),
        ("uniform_upper", uniform_upper, torch.float64),
        ("transition_ids", transition_ids, torch.uint64),
    )
    shape, device = head_fraction.shape, head_fraction.device
    for name, value, dtype in tensors:
        if (
            not isinstance(value, torch.Tensor)
            or not value.is_cuda
            or value.dtype != dtype
            or value.shape != shape
            or value.device != device
            or not value.is_contiguous()
        ):
            raise ValueError(
                f"{name} must be contiguous {dtype} on the common CUDA device"
            )
    count = int(head_fraction.numel())
    if count > 4096:
        raise ValueError("arbitrary-uniform Jacobi launches are capped at 4096")
    if not 128 <= int(mode_cap) <= 8192:
        raise ValueError("mode_cap must lie in [128,8192]")
    if bool((~torch.isfinite(exposure) | (exposure < 0.0)).any()):
        raise ValueError("exposure must be finite and nonnegative")
    if bool(
        (
            ~torch.isfinite(head_fraction)
            | (head_fraction < 0.0)
            | (head_fraction > 1.0)
        ).any()
    ):
        raise ValueError("head_fraction must be finite and lie in [0,1]")
    active = exposure > 0
    if bool(
        (
            active
            & (
                ~torch.isfinite(uniform_lower)
                | ~torch.isfinite(uniform_upper)
                | (uniform_lower <= 0.0)
                | (uniform_lower >= uniform_upper)
                | (uniform_upper >= 1.0)
            )
        ).any()
    ):
        raise ValueError("active uniform cells must lie strictly inside (0,1)")
    if (
        uniform_center_hi is None
        or uniform_center_lo is None
        or uniform_radius is None
    ):
        midpoint = uniform_lower + 0.5 * (uniform_upper - uniform_lower)
        uniform_center_hi = midpoint.contiguous()
        uniform_center_lo = torch.zeros_like(midpoint)
        base_radius = torch.maximum(
            midpoint - uniform_lower, uniform_upper - midpoint
        )
        uniform_radius = torch.nextafter(
            base_radius,
            torch.full_like(base_radius, math.inf),
        ).contiguous()
    for name, value in (
        ("uniform_center_hi", uniform_center_hi),
        ("uniform_center_lo", uniform_center_lo),
        ("uniform_radius", uniform_radius),
    ):
        if (
            not isinstance(value, torch.Tensor)
            or not value.is_cuda
            or value.dtype != torch.float64
            or value.shape != shape
            or value.device != device
            or not value.is_contiguous()
        ):
            raise ValueError(f"{name} must be contiguous float64 on CUDA")
    bundle = _compile(device)
    started = time.perf_counter()
    candidate = _launch_jacobi_candidate_from_uniform_midpoint(
        bundle,
        head_fraction,
        exposure,
        uniform_lower,
        uniform_upper,
        transition_ids,
        threads_per_block=int(threads_per_block),
    )
    later = head_fraction.clone()
    target = torch.zeros_like(head_fraction)
    qlo = head_fraction.clone()
    qhi = head_fraction.clone()
    zlo = torch.zeros_like(head_fraction)
    zhi = torch.zeros_like(head_fraction)
    modes = torch.zeros(count, dtype=torch.int32, device=device)
    codes = torch.zeros(count, dtype=torch.uint8, device=device)
    authorized = ~active
    reasons = torch.zeros(count, dtype=torch.uint8, device=device)
    launch_count = 0
    threads = int(threads_per_block)

    def candidate_at(base: Tensor, offset: int) -> Tensor:
        result = base
        direction = (
            torch.full_like(base, math.inf)
            if offset > 0
            else torch.full_like(base, -math.inf)
        )
        for _ in range(abs(int(offset))):
            result = torch.nextafter(result, direction)
        return result

    offsets = (
        0,
        0,
        -1,
        1,
        -2,
        2,
        -3,
        3,
        -4,
        4,
        -8,
        8,
        -16,
        16,
        -32,
        32,
        -64,
        64,
    )
    for attempt_index, offset in enumerate(offsets):
        unresolved = active & ~authorized
        if not bool(unresolved.any()):
            break
        indices = torch.nonzero(unresolved, as_tuple=False).reshape(-1)
        sub_count = int(indices.numel())
        sub_x = head_fraction.index_select(0, indices).contiguous()
        sub_u = exposure.index_select(0, indices).contiguous()
        sub_lo = uniform_lower.index_select(0, indices).contiguous()
        sub_hi = uniform_upper.index_select(0, indices).contiguous()
        sub_center_hi = uniform_center_hi.index_select(0, indices).contiguous()
        sub_center_lo = uniform_center_lo.index_select(0, indices).contiguous()
        sub_radius = uniform_radius.index_select(0, indices).contiguous()
        sub_candidate = candidate_at(
            candidate.index_select(0, indices).contiguous(), offset
        )
        sub_later = torch.empty_like(sub_x)
        sub_target = torch.empty_like(sub_x)
        sub_qlo = torch.empty_like(sub_x)
        sub_qhi = torch.empty_like(sub_x)
        sub_zlo = torch.empty_like(sub_x)
        sub_zhi = torch.empty_like(sub_x)
        sub_modes = torch.empty(sub_count, dtype=torch.int32, device=device)
        sub_codes = torch.empty(sub_count, dtype=torch.uint8, device=device)
        sub_authorized = torch.empty_like(sub_codes)
        sub_reasons = torch.empty_like(sub_codes)
        blocks = (sub_count + threads - 1) // threads
        bundle.uniform_authorizer(
            grid=(blocks, 1, 1),
            block=(threads, 1, 1),
            args=[
                sub_x,
                sub_u,
                sub_lo,
                sub_hi,
                sub_center_hi,
                sub_center_lo,
                sub_radius,
                sub_candidate,
                sub_count,
                int(mode_cap),
                sub_later,
                sub_target,
                sub_qlo,
                sub_qhi,
                sub_zlo,
                sub_zhi,
                sub_modes,
                sub_codes,
                sub_authorized,
                sub_reasons,
            ],
            stream=torch.cuda.current_stream(device),
        )
        launch_count += 1
        success = sub_authorized.bool()
        successful_indices = indices[success]
        if int(successful_indices.numel()):
            later.index_copy_(0, successful_indices, sub_later[success])
            target.index_copy_(0, successful_indices, sub_target[success])
            qlo.index_copy_(0, successful_indices, sub_qlo[success])
            qhi.index_copy_(0, successful_indices, sub_qhi[success])
            zlo.index_copy_(0, successful_indices, sub_zlo[success])
            zhi.index_copy_(0, successful_indices, sub_zhi[success])
            modes.index_copy_(0, successful_indices, sub_modes[success])
            codes.index_copy_(0, successful_indices, sub_codes[success])
            authorized[successful_indices] = True
        reasons.index_copy_(0, indices, sub_reasons)
        if attempt_index < 2:
            suggested = (
                ~success
                & (
                    (sub_reasons == 1)
                    | (sub_reasons == 23)
                    | (sub_reasons == 24)
                )
                & torch.isfinite(sub_later)
                & (sub_later > 0.0)
                & (sub_later < 1.0)
            )
            if bool(suggested.any()):
                candidate.index_copy_(0, indices[suggested], sub_later[suggested])
    torch.cuda.synchronize(device)
    return HaarUniformFusedLaunch(
        later=later,
        target=target,
        quantile_lower=qlo,
        quantile_upper=qhi,
        target_lower=zlo,
        target_upper=zhi,
        modes_used=modes,
        certificate_codes=codes,
        authorized_mask=authorized,
        fallback_reason_codes=reasons,
        candidate=candidate,
        launch_count=launch_count,
        elapsed_seconds=time.perf_counter() - started,
        bundle=bundle,
    )


def fused_haar_runtime_report(device: Any | None = None) -> dict[str, Any]:
    report = verify_normal_constants()
    report.update(
        compile_flags=list(HAAR_FUSED_COMPILE_FLAGS),
        source_bits=HAAR_NORMAL_SOURCE_BITS,
        maximum_sources=HAAR_NORMAL_MAX_SOURCES,
        torch_version=None if torch is None else str(torch.__version__),
        torch_cuda_build=None if torch is None else str(torch.version.cuda),
        cuda_driver_api_version=_cuda_driver_api_version(),
        cuda_available=bool(torch is not None and torch.cuda.is_available()),
        fused_cuda_normal_authorizer_available=False,
    )
    if device is None or torch is None or not torch.cuda.is_available():
        return report
    try:
        bundle = _compile(device)
        props = torch.cuda.get_device_properties(torch.device(device))
        report.update(
            fused_cuda_normal_authorizer_available=True,
            binary_sha256=bundle.binary_sha256,
            source_sha256=bundle.source_sha256,
            constants_sha256=bundle.constants_sha256,
            selftest_mask=bundle.selftest_mask,
            device_name=str(props.name),
            compute_capability=f"{props.major}.{props.minor}",
            compile_target=f"sm_{props.major}{props.minor}",
            device_uuid=str(props.uuid),
            pci_bus_id=int(props.pci_bus_id),
            pci_device_id=int(props.pci_device_id),
        )
    except Exception as exc:
        report["compile_error"] = f"{type(exc).__name__}: {exc}"
    return report


__all__ = [
    "HAAR_FUSED_COMPILE_FLAGS",
    "HAAR_FUSED_CUDA_VERSION",
    "HAAR_NORMAL_MAX_SOURCES",
    "HAAR_NORMAL_REQUIRED_SELFTEST_MASK",
    "HaarFusedBundle",
    "HaarFusedCudaError",
    "HaarFusedLaunch",
    "HaarUniformFusedLaunch",
    "canonical_haar_seed",
    "fused_haar_runtime_report",
    "launch_certified_jacobi_from_uniform_cells",
    "launch_certified_haar_normal_transform",
    "launch_certified_normal_prefix_transform",
    "verify_normal_constants",
]
