"""H1 function-step trust helpers for D0 density-ratio controls.

The balanced BCE remains the scientific population objective.  This module
only supplies a moving, stopped-EMA proximal term on the *increment* of the
raw logit.  In particular, it deliberately does not penalize the absolute
Dirichlet energy of the learned logit, which would move the Bayes optimum.

For ``d = ell_raw - stop_gradient(ell_ema)`` the normalized fixed-grid
components are

``V(d) = E_nu[d ** 2]`` and

``G(d) = E_nu[Gamma_h(d, d) / (2 N ** 2)]``
       ``= E_nu[mean_e theta_e r_e(d) ** 2]``.

The reference states are generated by a stateless ``Dirichlet(1)`` stream.
They are independent of candidate ordering and use the same frozen five-bin
time design for teacher and null tasks.  No sampler functionality belongs in
this module.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import hashlib
import json
import math
from collections.abc import Mapping, Sequence
from typing import Any

import numpy as np
import torch
from torch import Tensor, nn

from .d0_dirichlet_score import (
    edge_difference_channels,
    harmonic_mobility_exact,
    physical_flux_from_edge_score,
)
from .eulerian_flux_mnist import DirectFluxMNISTConfig


H1_TRUST_SCHEMA = "experiment12-d0-score-density-ratio-h1-trust"
H1_TRUST_SCHEMA_VERSION = 1
H1_TRUST_STREAM_VERSION = "d0-reference-h1-trust-stream-v1"
H1_TRUST_OPERATOR_VERSION = "d0-stopped-ema-l2-gamma-increment-v1"
H1_TRUST_CALIBRATION_VERSION = "d0-one-shadow-step-h1-calibration-v1"

H1_TRUST_PRODUCTION_ROOT_SEED = 261001
H1_TRUST_BANKS_PER_UPDATE = 2
H1_TRUST_STATES_PER_BANK = 32
H1_TRUST_BIN_COUNTS = (4, 4, 4, 4, 16)
H1_TRUST_SCALE_FLOOR = 1e-8
H1_TRUST_TASKS = ("bounded_teacher", "dirichlet_null")


__all__ = [
    "H1_TRUST_SCHEMA",
    "H1_TRUST_SCHEMA_VERSION",
    "H1_TRUST_STREAM_VERSION",
    "H1_TRUST_OPERATOR_VERSION",
    "H1_TRUST_CALIBRATION_VERSION",
    "H1_TRUST_PRODUCTION_ROOT_SEED",
    "H1_TRUST_BANKS_PER_UPDATE",
    "H1_TRUST_STATES_PER_BANK",
    "H1_TRUST_BIN_COUNTS",
    "H1_TRUST_SCALE_FLOOR",
    "H1_TRUST_TASKS",
    "H1TrustPlan",
    "ReferenceTrustBatch",
    "H1IncrementComponents",
    "H1TrustCalibration",
    "build_h1_trust_plan",
    "h1_trust_plan_record",
    "derive_reference_trust_seed",
    "generate_reference_trust_batch",
    "h1_increment_components",
    "calibrate_h1_trust",
]


def _canonical_json(value: Any) -> bytes:
    return json.dumps(
        value, sort_keys=True, separators=(",", ":"), ensure_ascii=True
    ).encode("utf-8")


def _canonical_fingerprint(value: Any) -> str:
    return hashlib.sha256(_canonical_json(value)).hexdigest()


def _tensor_fingerprint(value: Tensor) -> str:
    tensor = value.detach().cpu().contiguous()
    array = tensor.numpy()
    digest = hashlib.sha256()
    digest.update(str(array.dtype).encode("ascii"))
    digest.update(_canonical_json(list(array.shape)))
    digest.update(array.tobytes(order="C"))
    return digest.hexdigest()


def _array_fingerprint(value: np.ndarray) -> str:
    array = np.ascontiguousarray(value)
    digest = hashlib.sha256()
    digest.update(str(array.dtype).encode("ascii"))
    digest.update(_canonical_json(list(array.shape)))
    digest.update(array.tobytes(order="C"))
    return digest.hexdigest()


def _task(value: str) -> str:
    result = str(value).strip().lower()
    if result not in H1_TRUST_TASKS:
        raise ValueError(f"task must be one of {H1_TRUST_TASKS}")
    return result


def _finite_positive(value: float) -> bool:
    return math.isfinite(float(value)) and float(value) > 0.0


@dataclass(frozen=True)
class H1TrustPlan:
    """Immutable stateless reference-stream plan for the H1 trust term."""

    grid_size: int
    horizon: float
    root_seed: int = H1_TRUST_PRODUCTION_ROOT_SEED
    label: int = 3
    banks_per_update: int = H1_TRUST_BANKS_PER_UPDATE
    states_per_bank: int = H1_TRUST_STATES_PER_BANK
    bin_counts: tuple[int, ...] = H1_TRUST_BIN_COUNTS
    schema: str = H1_TRUST_SCHEMA + "-plan"
    schema_version: int = H1_TRUST_SCHEMA_VERSION
    stream_version: str = H1_TRUST_STREAM_VERSION

    def __post_init__(self) -> None:
        if int(self.grid_size) <= 1:
            raise ValueError("grid_size must be greater than one")
        if not _finite_positive(float(self.horizon)):
            raise ValueError("horizon must be finite and positive")
        if int(self.root_seed) < 0:
            raise ValueError("root_seed must be nonnegative")
        if int(self.label) < 0:
            raise ValueError("label must be nonnegative")
        if int(self.banks_per_update) != H1_TRUST_BANKS_PER_UPDATE:
            raise ValueError("H1 trust v1 freezes two banks per update")
        if int(self.states_per_bank) != H1_TRUST_STATES_PER_BANK:
            raise ValueError("H1 trust v1 freezes 32 states per bank")
        if tuple(int(value) for value in self.bin_counts) != H1_TRUST_BIN_COUNTS:
            raise ValueError("H1 trust v1 freezes time strata 4,4,4,4,16")
        if sum(int(value) for value in self.bin_counts) != int(
            self.states_per_bank
        ):
            raise ValueError("bin_counts must sum to states_per_bank")

    @property
    def pixels(self) -> int:
        return int(self.grid_size) ** 2

    @property
    def fingerprint(self) -> str:
        return _canonical_fingerprint(_plan_payload(self))


def _plan_payload(plan: H1TrustPlan) -> dict[str, Any]:
    return {
        "schema": str(plan.schema),
        "schema_version": int(plan.schema_version),
        "stream_version": str(plan.stream_version),
        "operator_version": H1_TRUST_OPERATOR_VERSION,
        "root_seed": int(plan.root_seed),
        "grid_size": int(plan.grid_size),
        "pixels": int(plan.pixels),
        "horizon": float(plan.horizon),
        "label": int(plan.label),
        "banks_per_update": int(plan.banks_per_update),
        "states_per_bank": int(plan.states_per_bank),
        "bin_counts": [int(value) for value in plan.bin_counts],
        "candidate_fields_in_seed": [],
        "reference_law": "Dirichlet(1)",
    }


def build_h1_trust_plan(
    *,
    grid_size: int,
    horizon: float,
    root_seed: int = H1_TRUST_PRODUCTION_ROOT_SEED,
    label: int = 3,
) -> H1TrustPlan:
    return H1TrustPlan(
        grid_size=int(grid_size),
        horizon=float(horizon),
        root_seed=int(root_seed),
        label=int(label),
    )


def h1_trust_plan_record(plan: H1TrustPlan) -> dict[str, Any]:
    return {
        **_plan_payload(plan),
        "fingerprint": plan.fingerprint,
        "physical_training_performed": 0,
        "sampling_performed": 0,
    }


def derive_reference_trust_seed(
    plan_or_root_seed: H1TrustPlan | int,
    phase: str,
    task: str,
    optimizer_step: int,
    bank: int,
    namespace: str,
) -> int:
    """Derive a candidate-independent seed for one trust-stream component."""

    root_seed = (
        int(plan_or_root_seed.root_seed)
        if isinstance(plan_or_root_seed, H1TrustPlan)
        else int(plan_or_root_seed)
    )
    phase_value = str(phase).strip()
    task_value = _task(task)
    namespace_value = str(namespace).strip()
    if not phase_value or not namespace_value:
        raise ValueError("phase and namespace must be nonempty")
    if int(optimizer_step) < 0:
        raise ValueError("optimizer_step must be nonnegative")
    if int(bank) < 0 or int(bank) >= H1_TRUST_BANKS_PER_UPDATE:
        raise ValueError("bank must be zero or one")
    payload = [
        H1_TRUST_STREAM_VERSION,
        root_seed,
        phase_value,
        task_value,
        int(optimizer_step),
        int(bank),
        namespace_value,
    ]
    return int.from_bytes(hashlib.sha256(_canonical_json(payload)).digest()[:8], "little") & (
        (1 << 63) - 1
    )


def _time_template(dtype: torch.dtype) -> tuple[Tensor, np.ndarray, np.ndarray]:
    fractions: list[float] = []
    strata: list[int] = []
    anchors: list[int] = []
    anchor = 0
    for bin_index, count in enumerate(H1_TRUST_BIN_COUNTS):
        for offset in range(int(count)):
            fractions.append(
                (float(bin_index) + (float(offset) + 0.5) / float(count)) / 5.0
            )
            strata.append(int(bin_index))
            anchors.append(anchor)
            anchor += 1
    return (
        torch.tensor(fractions, dtype=dtype),
        np.asarray(strata, dtype=np.int64),
        np.asarray(anchors, dtype=np.int64),
    )


@dataclass(frozen=True)
class ReferenceTrustBatch:
    """One deterministic 32-state reference-law H1 trust bank."""

    states: Tensor
    tau: Tensor
    tau_fraction: Tensor
    labels: Tensor
    strata: np.ndarray
    anchor_ids: np.ndarray
    phase: str
    task: str
    optimizer_step: int
    bank: int
    gamma_seed: int
    permutation_seed: int
    plan_fingerprint: str
    fingerprint: str

    def __post_init__(self) -> None:
        rows = H1_TRUST_STATES_PER_BANK
        if self.states.ndim != 2 or self.states.shape[0] != rows:
            raise ValueError("reference trust states must have shape (32, N)")
        if any(value.shape != (rows,) for value in (self.tau, self.tau_fraction, self.labels)):
            raise ValueError("tau, tau_fraction, and labels must have shape (32,)")
        if any(np.asarray(value).shape != (rows,) for value in (self.strata, self.anchor_ids)):
            raise ValueError("strata and anchor_ids must have shape (32,)")
        if not bool(torch.isfinite(self.states).all() and (self.states > 0.0).all()):
            raise ValueError("reference trust states must be finite and positive")
        simplex_error = float(
            (self.states.sum(dim=1) - 1.0).abs().max().detach().cpu()
        )
        tolerance = 5e-6 if self.states.dtype == torch.float32 else 1e-12
        if simplex_error > tolerance:
            raise ValueError("reference trust states must lie on the simplex")
        counts = tuple(
            int(np.count_nonzero(np.asarray(self.strata) == index))
            for index in range(5)
        )
        if counts != H1_TRUST_BIN_COUNTS:
            raise ValueError("reference trust batch has the wrong time strata")
        _task(self.task)
        if int(self.optimizer_step) < 0 or int(self.bank) not in (0, 1):
            raise ValueError("invalid reference trust stream cursor")

    @property
    def size(self) -> int:
        return int(self.states.shape[0])

    def record(self) -> dict[str, Any]:
        return {
            "schema": H1_TRUST_SCHEMA + "-reference-batch",
            "schema_version": H1_TRUST_SCHEMA_VERSION,
            "stream_version": H1_TRUST_STREAM_VERSION,
            "reference_law": "Dirichlet(1)",
            "phase": str(self.phase),
            "task": str(self.task),
            "optimizer_step": int(self.optimizer_step),
            "bank": int(self.bank),
            "states": int(self.size),
            "pixels": int(self.states.shape[1]),
            "gamma_seed": int(self.gamma_seed),
            "permutation_seed": int(self.permutation_seed),
            "state_sha256": _tensor_fingerprint(self.states),
            "tau_fraction_sha256": _tensor_fingerprint(self.tau_fraction),
            "strata_sha256": _array_fingerprint(np.asarray(self.strata)),
            "anchor_ids_sha256": _array_fingerprint(np.asarray(self.anchor_ids)),
            "plan_fingerprint": str(self.plan_fingerprint),
            "fingerprint": str(self.fingerprint),
            "candidate_independent": 1,
            "physical_training_performed": 0,
            "sampling_performed": 0,
        }


def generate_reference_trust_batch(
    plan: H1TrustPlan,
    *,
    phase: str,
    task: str,
    optimizer_step: int,
    bank: int,
    device: torch.device | str = "cpu",
    dtype: torch.dtype = torch.float32,
) -> ReferenceTrustBatch:
    """Generate one replayable reference-law bank without candidate inputs."""

    if dtype not in (torch.float32, torch.float64):
        raise ValueError("reference trust dtype must be float32 or float64")
    phase_value = str(phase).strip()
    task_value = _task(task)
    if not phase_value:
        raise ValueError("phase must be nonempty")
    step_value = int(optimizer_step)
    bank_value = int(bank)
    gamma_seed = derive_reference_trust_seed(
        plan, phase_value, task_value, step_value, bank_value, "reference-gamma"
    )
    permutation_seed = derive_reference_trust_seed(
        plan, phase_value, task_value, step_value, bank_value, "row-permutation"
    )
    generator = torch.Generator(device="cpu").manual_seed(gamma_seed)
    gamma = torch._standard_gamma(
        torch.ones((plan.states_per_bank, plan.pixels), dtype=dtype),
        generator=generator,
    )
    states = gamma / gamma.sum(dim=1, keepdim=True)
    fractions, strata, anchor_ids = _time_template(dtype)
    permutation_generator = torch.Generator(device="cpu").manual_seed(permutation_seed)
    permutation = torch.randperm(plan.states_per_bank, generator=permutation_generator)
    permutation_np = permutation.numpy()
    states = states.index_select(0, permutation).contiguous()
    fractions = fractions.index_select(0, permutation).contiguous()
    strata = strata[permutation_np]
    anchor_ids = anchor_ids[permutation_np]
    tau = fractions * float(plan.horizon)
    labels = torch.full((plan.states_per_bank,), int(plan.label), dtype=torch.long)
    payload = {
        "schema": H1_TRUST_SCHEMA + "-reference-batch",
        "schema_version": H1_TRUST_SCHEMA_VERSION,
        "stream_version": H1_TRUST_STREAM_VERSION,
        "phase": phase_value,
        "task": task_value,
        "optimizer_step": step_value,
        "bank": bank_value,
        "gamma_seed": gamma_seed,
        "permutation_seed": permutation_seed,
        "state_sha256": _tensor_fingerprint(states),
        "tau_fraction_sha256": _tensor_fingerprint(fractions),
        "strata_sha256": _array_fingerprint(strata),
        "anchor_ids_sha256": _array_fingerprint(anchor_ids),
        "plan_fingerprint": plan.fingerprint,
    }
    fingerprint = _canonical_fingerprint(payload)
    target = torch.device(device)
    return ReferenceTrustBatch(
        states=states.to(target),
        tau=tau.to(target),
        tau_fraction=fractions.to(target),
        labels=labels.to(target),
        strata=strata,
        anchor_ids=anchor_ids,
        phase=phase_value,
        task=task_value,
        optimizer_step=step_value,
        bank=bank_value,
        gamma_seed=gamma_seed,
        permutation_seed=permutation_seed,
        plan_fingerprint=plan.fingerprint,
        fingerprint=fingerprint,
    )


def _model_logits(
    model: nn.Module, tau: Tensor, states: Tensor, labels: Tensor
) -> Tensor:
    logits = model(tau, states, labels)
    if logits.shape != (states.shape[0],):
        raise ValueError("H1 trust model must return one raw logit per state")
    if not bool(torch.isfinite(logits).all()):
        raise FloatingPointError("H1 trust logits are nonfinite")
    return logits


def _state_gradient(logits: Tensor, states: Tensor, *, create_graph: bool) -> Tensor:
    gradient = torch.autograd.grad(
        logits.sum(),
        states,
        create_graph=bool(create_graph),
        retain_graph=bool(create_graph),
        allow_unused=True,
    )[0]
    if gradient is None:
        gradient = torch.zeros_like(states)
    if not bool(torch.isfinite(gradient).all()):
        raise FloatingPointError("H1 trust state gradient is nonfinite")
    return gradient


@dataclass(frozen=True)
class H1IncrementComponents:
    """Differentiable stopped-EMA H1 increment and detached diagnostics."""

    per_state_value: Tensor
    per_state_natural_energy: Tensor
    per_state_physical_flux_energy: Tensor
    value_mean: Tensor
    natural_energy_mean: Tensor
    physical_flux_energy_mean: Tensor
    normalized_value: Tensor
    normalized_natural_energy: Tensor
    objective: Tensor
    value_scale: float
    energy_scale: float

    def detached_record(self) -> dict[str, Any]:
        value = float(self.value_mean.detach().cpu())
        natural = float(self.natural_energy_mean.detach().cpu())
        physical = float(self.physical_flux_energy_mean.detach().cpu())
        return {
            "operator_version": H1_TRUST_OPERATOR_VERSION,
            "value_mse": value,
            "value_rms": math.sqrt(max(0.0, value)),
            "natural_energy": natural,
            "natural_energy_rms": math.sqrt(max(0.0, natural)),
            "physical_flux_energy": physical,
            "physical_flux_step_rms": math.sqrt(max(0.0, physical)),
            "value_scale": float(self.value_scale),
            "energy_scale": float(self.energy_scale),
            "normalized_value": float(self.normalized_value.detach().cpu()),
            "normalized_natural_energy": float(
                self.normalized_natural_energy.detach().cpu()
            ),
            "normalized_h1_objective": float(self.objective.detach().cpu()),
            "physical_training_performed": 0,
            "sampling_performed": 0,
        }


def h1_increment_components(
    model: nn.Module,
    ema_model: nn.Module,
    tau: Tensor,
    states: Tensor,
    labels: Tensor,
    dynamics: DirectFluxMNISTConfig,
    *,
    value_scale: float,
    energy_scale: float,
    create_graph: bool,
) -> H1IncrementComponents:
    """Evaluate the full L2-plus-Dirichlet stopped-EMA logit increment.

    ``ema_model`` is an anchor only.  Its logits and state gradients are
    detached before forming the increment, so the returned objective never
    differentiates through EMA parameters.  The natural energy uses every one
    of the ``2N`` oriented periodic edges; there is no Hutchinson or edge probe.
    """

    value_scale_value = float(value_scale)
    energy_scale_value = float(energy_scale)
    if not _finite_positive(value_scale_value):
        raise ValueError("value_scale must be finite and positive")
    if not _finite_positive(energy_scale_value):
        raise ValueError("energy_scale must be finite and positive")
    if states.ndim != 2 or states.shape[1] != int(dynamics.grid_size) ** 2:
        raise ValueError("states have the wrong fixed-grid shape")
    if tau.shape != (states.shape[0],) or labels.shape != (states.shape[0],):
        raise ValueError("tau and labels must match the state batch")
    if not bool(torch.isfinite(states).all()):
        raise FloatingPointError("H1 trust states are nonfinite")

    # A distinct state leaf keeps the stopped EMA derivative graph completely
    # separate from the trainable graph.  autograd.grad does not populate EMA
    # parameter .grad fields, and both returned anchor tensors are detached.
    anchor_states = states.detach().clone().requires_grad_(True)
    anchor_was_training = ema_model.training
    ema_model.eval()
    try:
        anchor_logits_graph = _model_logits(ema_model, tau, anchor_states, labels)
        anchor_gradient = _state_gradient(
            anchor_logits_graph, anchor_states, create_graph=False
        ).detach()
        anchor_logits = anchor_logits_graph.detach()
    finally:
        ema_model.train(anchor_was_training)

    current_states = states.detach().clone().requires_grad_(True)
    current_logits = _model_logits(model, tau, current_states, labels)
    current_gradient = _state_gradient(
        current_logits, current_states, create_graph=bool(create_graph)
    )
    delta_logits = current_logits - anchor_logits
    delta_gradient = current_gradient - anchor_gradient
    edge_delta = edge_difference_channels(delta_gradient, int(dynamics.grid_size))
    theta = harmonic_mobility_exact(current_states.detach(), dynamics).detach()
    natural_per_state = (theta * edge_delta.square()).flatten(1).mean(dim=1)
    physical_flux = physical_flux_from_edge_score(
        edge_delta, current_states.detach(), dynamics, time_change=1.0
    )
    physical_per_state = physical_flux.square().flatten(1).mean(dim=1)
    value_per_state = delta_logits.square()
    finite = bool(
        torch.isfinite(value_per_state).all()
        and torch.isfinite(natural_per_state).all()
        and torch.isfinite(physical_per_state).all()
    )
    if not finite:
        raise FloatingPointError("H1 increment components are nonfinite")

    value_mean = value_per_state.mean()
    natural_mean = natural_per_state.mean()
    physical_mean = physical_per_state.mean()
    normalized_value = value_mean / (value_scale_value * value_scale_value)
    normalized_energy = natural_mean / (energy_scale_value * energy_scale_value)
    objective = 0.5 * (normalized_value + normalized_energy)
    return H1IncrementComponents(
        per_state_value=value_per_state,
        per_state_natural_energy=natural_per_state,
        per_state_physical_flux_energy=physical_per_state,
        value_mean=value_mean,
        natural_energy_mean=natural_mean,
        physical_flux_energy_mean=physical_mean,
        normalized_value=normalized_value,
        normalized_natural_energy=normalized_energy,
        objective=objective,
        value_scale=value_scale_value,
        energy_scale=energy_scale_value,
    )


def _gradient_norm(loss: Tensor, model: nn.Module) -> float:
    parameters = tuple(parameter for parameter in model.parameters() if parameter.requires_grad)
    if not parameters or not loss.requires_grad:
        return 0.0
    gradients = torch.autograd.grad(
        loss, parameters, allow_unused=True, retain_graph=False, create_graph=False
    )
    squared = loss.detach().new_zeros(())
    for gradient in gradients:
        if gradient is not None:
            squared = squared + gradient.detach().square().sum()
    return float(torch.sqrt(squared).detach().cpu())


def _stack_batches(
    batches: ReferenceTrustBatch | Sequence[ReferenceTrustBatch],
) -> tuple[Tensor, Tensor, Tensor, list[str], str, str, int]:
    values = [batches] if isinstance(batches, ReferenceTrustBatch) else list(batches)
    if not values:
        raise ValueError("at least one reference trust batch is required")
    first = values[0]
    if any(
        value.plan_fingerprint != first.plan_fingerprint
        or value.phase != first.phase
        or value.task != first.task
        or int(value.optimizer_step) != int(first.optimizer_step)
        for value in values
    ):
        raise ValueError("calibration trust batches must share one stream binding")
    banks = [int(value.bank) for value in values]
    if len(set(banks)) != len(banks):
        raise ValueError("calibration trust banks must be distinct")
    return (
        torch.cat([value.states for value in values], dim=0),
        torch.cat([value.tau for value in values], dim=0),
        torch.cat([value.labels for value in values], dim=0),
        [str(value.fingerprint) for value in values],
        str(first.phase),
        str(first.task),
        int(first.optimizer_step),
    )


@dataclass(frozen=True)
class H1TrustCalibration:
    """Serializable one-shadow-step calibration for the H1 multiplier."""

    calibration_state_count: int
    trust_batch_fingerprints: tuple[str, ...]
    phase: str
    task: str
    optimizer_step: int
    value_scale: float
    energy_scale: float
    raw_value_rms: float
    raw_natural_energy_rms: float
    raw_physical_flux_step_rms: float
    scaled_bce_gradient_norm: float
    normalized_h1_gradient_norm: float
    lambda_base: float | None
    scale_floor: float
    value_scale_floor_hit: int
    energy_scale_floor_hit: int
    bce_gradient_floor_hit: int
    h1_gradient_floor_hit: int
    passed: int
    binding: dict[str, Any]
    schema: str = H1_TRUST_SCHEMA + "-calibration"
    schema_version: int = H1_TRUST_SCHEMA_VERSION
    calibration_version: str = H1_TRUST_CALIBRATION_VERSION
    calibration_split: str = "train"
    training_only: int = 1
    shadow_steps: int = 1
    physical_training_performed: int = 0
    sampling_performed: int = 0

    def to_record(self) -> dict[str, Any]:
        return asdict(self)


def calibrate_h1_trust(
    shadow_model: nn.Module,
    prestep_ema_model: nn.Module,
    batches: ReferenceTrustBatch | Sequence[ReferenceTrustBatch],
    dynamics: DirectFluxMNISTConfig,
    *,
    scaled_bce_gradient_norm: float,
    scale_floor: float = H1_TRUST_SCALE_FLOOR,
    binding: Mapping[str, Any] | None = None,
) -> H1TrustCalibration:
    """Calibrate scales and the base H1 multiplier from one shadow step.

    The caller owns the deterministic BCE shadow update and passes the norm of
    its normalized-coordinate, scaled-BCE gradient.  ``shadow_model`` is the
    post-shadow-step raw model; ``prestep_ema_model`` is the stopped EMA anchor
    from immediately before that step.  The value and energy RMS values become
    frozen scales.  ``lambda_base`` makes the normalized H1 gradient norm equal
    to the supplied scaled-BCE gradient norm at calibration.

    Every floor hit is represented explicitly and makes ``passed == 0``.  The
    clamped scales are still recorded so a failed calibration remains fully
    reportable, but its ``lambda_base`` is ``None`` and must not be trained.
    """

    floor = float(scale_floor)
    bce_norm = float(scaled_bce_gradient_norm)
    if not _finite_positive(floor):
        raise ValueError("scale_floor must be finite and positive")
    if not math.isfinite(bce_norm) or bce_norm < 0.0:
        raise ValueError("scaled_bce_gradient_norm must be finite and nonnegative")
    states, tau, labels, fingerprints, phase, task, step = _stack_batches(batches)

    raw = h1_increment_components(
        shadow_model,
        prestep_ema_model,
        tau,
        states,
        labels,
        dynamics,
        value_scale=1.0,
        energy_scale=1.0,
        create_graph=False,
    )
    value_rms = math.sqrt(max(0.0, float(raw.value_mean.detach().cpu())))
    energy_rms = math.sqrt(
        max(0.0, float(raw.natural_energy_mean.detach().cpu()))
    )
    physical_rms = math.sqrt(
        max(0.0, float(raw.physical_flux_energy_mean.detach().cpu()))
    )
    value_hit = int(not math.isfinite(value_rms) or value_rms <= floor)
    energy_hit = int(not math.isfinite(energy_rms) or energy_rms <= floor)
    bce_hit = int(not math.isfinite(bce_norm) or bce_norm <= floor)
    value_scale = max(floor, value_rms) if math.isfinite(value_rms) else floor
    energy_scale = max(floor, energy_rms) if math.isfinite(energy_rms) else floor

    normalized = h1_increment_components(
        shadow_model,
        prestep_ema_model,
        tau,
        states,
        labels,
        dynamics,
        value_scale=value_scale,
        energy_scale=energy_scale,
        create_graph=True,
    )
    h1_norm = _gradient_norm(normalized.objective, shadow_model)
    h1_hit = int(not math.isfinite(h1_norm) or h1_norm <= floor)
    passed = int(not any((value_hit, energy_hit, bce_hit, h1_hit)))
    multiplier = bce_norm / h1_norm if passed else None
    if multiplier is not None and not _finite_positive(multiplier):
        multiplier = None
        passed = 0
        h1_hit = 1

    return H1TrustCalibration(
        calibration_state_count=int(states.shape[0]),
        trust_batch_fingerprints=tuple(fingerprints),
        phase=phase,
        task=task,
        optimizer_step=step,
        value_scale=float(value_scale),
        energy_scale=float(energy_scale),
        raw_value_rms=float(value_rms),
        raw_natural_energy_rms=float(energy_rms),
        raw_physical_flux_step_rms=float(physical_rms),
        scaled_bce_gradient_norm=float(bce_norm),
        normalized_h1_gradient_norm=float(h1_norm),
        lambda_base=None if multiplier is None else float(multiplier),
        scale_floor=floor,
        value_scale_floor_hit=int(value_hit),
        energy_scale_floor_hit=int(energy_hit),
        bce_gradient_floor_hit=int(bce_hit),
        h1_gradient_floor_hit=int(h1_hit),
        passed=int(passed),
        binding={} if binding is None else dict(binding),
    )
