from __future__ import annotations

r"""Example 9: Eulerian image-mass bridge from a house to a butterfly.

This module is a runnable companion to the fixed-grid terminal-conditioning
recipe in the manuscript.  A grayscale image is represented by a point in the
``28 x 28`` probability simplex.  The target image enters through a positive
Gibbs terminal score ``g_h``.  The backward heat potential

    u_t^h(s) = E_s[g_h(S^h(T - t))]

is approximated by a positive convolutional surrogate trained from free
Eulerian rollouts.  A conditioned sample path is then generated by adding the
edge flux

    (2 / h) theta_e(s) partial_e^h u_t^h(s) / u_t^h(s)

to the conservative free edge flux.

The code is intentionally small and notebook-friendly.  It is meant as a
numerically stable experiment scaffold, not as a tuned image-generation system.
"""

import math
from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

import torch
from torch import Tensor, nn
from torch.nn import functional as F

FloatArray = NDArray[np.float64]

__all__ = [
    "EulerianImageBridgeConfig",
    "EulerianRollout",
    "ConditionedBridgeResult",
    "RegressionBatch",
    "PositiveHeatPotentialCNN",
    "make_synthetic_house_image",
    "make_synthetic_butterfly_image",
    "normalize_image_to_measure",
    "natural_horizon",
    "terminal_potential_numpy",
    "terminal_preference_numpy",
    "terminal_potential_torch",
    "terminal_preference_torch",
    "sample_proposal_states",
    "simulate_free_rollout",
    "make_feynman_kac_regression_batch",
    "train_heat_potential_surrogate",
    "simulate_conditioned_image_bridge",
]


@dataclass(frozen=True)
class EulerianImageBridgeConfig:
    """Numerical knobs for the fixed-grid image bridge.

    Parameters
    ----------
    grid_size:
        Number of pixels per side.  The intended experiment uses ``28``.
    alpha:
        Per-cell Dirichlet parameter used by the fixed-grid simulator.  For a
        single visual experiment, ``alpha=1`` is much better conditioned than a
        tiny continuum-scaled value.
    horizon_scale:
        The physical horizon is ``horizon_scale / ((2 * alpha + 1) * n**2)``.
        This keeps the drift time scale comparable as ``n`` changes.
    num_steps:
        Default number of Euler edge-splitting steps for a full-horizon rollout.
    limiter_fraction:
        Maximum fraction of an endpoint mass that a single split-edge update may
        move across that edge.  This prevents explicit Euler overshoots at the
        simplex boundary.
    terminal_lambda:
        Sharpness of the butterfly terminal preference.
    terminal_floor:
        Positive lower bound added to the Gibbs score.  This keeps ``u`` safely
        positive and prevents division by nearly-zero surrogate values.
    blur_sigmas, blur_weights:
        Multi-scale blur parameters for the terminal discrepancy.  Using blurred
        terms first is more stable than a sharp pixelwise target.
    """

    grid_size: int = 28
    alpha: float = 1.0
    horizon_scale: float = 2.0
    num_steps: int = 4000
    limiter_fraction: float = 0.25
    terminal_lambda: float = 4.0
    terminal_floor: float = 1e-4
    blur_sigmas: tuple[float, ...] = (1.0, 2.0)
    blur_weights: tuple[float, ...] = (0.4, 0.6)
    mass_floor: float = 1e-8
    value_floor: float = 1e-8

    def __post_init__(self) -> None:
        if self.grid_size <= 1:
            raise ValueError("grid_size must be at least 2")
        if self.grid_size % 2 != 0:
            raise ValueError("grid_size must be even for the four-color edge splitter")
        if self.alpha <= 0.0 or not math.isfinite(self.alpha):
            raise ValueError("alpha must be positive and finite")
        if self.horizon_scale <= 0.0 or not math.isfinite(self.horizon_scale):
            raise ValueError("horizon_scale must be positive and finite")
        if self.num_steps <= 0:
            raise ValueError("num_steps must be positive")
        if not (0.0 < self.limiter_fraction <= 1.0):
            raise ValueError("limiter_fraction must be in (0, 1]")
        if self.terminal_lambda < 0.0 or not math.isfinite(self.terminal_lambda):
            raise ValueError("terminal_lambda must be non-negative and finite")
        if not (0.0 < self.terminal_floor < 1.0):
            raise ValueError("terminal_floor must be in (0, 1)")
        if len(self.blur_sigmas) != len(self.blur_weights):
            raise ValueError("blur_sigmas and blur_weights must have equal length")
        if len(self.blur_sigmas) == 0:
            raise ValueError("at least one blur scale is required")
        if any(sigma < 0.0 for sigma in self.blur_sigmas):
            raise ValueError("blur_sigmas must be non-negative")
        if any(weight < 0.0 for weight in self.blur_weights):
            raise ValueError("blur_weights must be non-negative")
        if sum(self.blur_weights) <= 0.0:
            raise ValueError("at least one blur weight must be positive")
        if self.mass_floor <= 0.0:
            raise ValueError("mass_floor must be positive")
        if self.value_floor <= 0.0:
            raise ValueError("value_floor must be positive")


@dataclass(frozen=True)
class EulerianRollout:
    """Free Eulerian rollout result."""

    times: FloatArray
    trajectory: FloatArray
    final_state: FloatArray
    clipping_fraction: float


@dataclass(frozen=True)
class ConditionedBridgeResult:
    """Conditioned image bridge path and diagnostics."""

    times: FloatArray
    trajectory: FloatArray
    terminal_scores: FloatArray
    clipping_fraction: float


@dataclass(frozen=True)
class RegressionBatch:
    """Supervised Feynman--Kac regression batch."""

    tau: FloatArray
    states: FloatArray
    targets: FloatArray


# ---------------------------------------------------------------------------
# Synthetic example images and terminal preference
# ---------------------------------------------------------------------------


def make_synthetic_house_image(grid_size: int = 28) -> FloatArray:
    """Return a simple ``grid_size x grid_size`` grayscale house image."""
    if grid_size <= 1:
        raise ValueError("grid_size must be at least 2")
    yy, xx = np.mgrid[0:grid_size, 0:grid_size]
    x = (xx + 0.5) / float(grid_size)
    y = (yy + 0.5) / float(grid_size)

    body = (0.23 <= x) & (x <= 0.77) & (0.45 <= y) & (y <= 0.86)
    roof = (0.16 <= x) & (x <= 0.84) & (0.20 <= y) & (y <= 0.52)
    roof &= y >= 0.20 + 0.70 * np.abs(x - 0.50)
    door = (0.45 <= x) & (x <= 0.56) & (0.65 <= y) & (y <= 0.86)
    left_window = (0.31 <= x) & (x <= 0.40) & (0.55 <= y) & (y <= 0.65)
    right_window = (0.61 <= x) & (x <= 0.70) & (0.55 <= y) & (y <= 0.65)
    chimney = (0.65 <= x) & (x <= 0.73) & (0.18 <= y) & (y <= 0.36)

    image = np.zeros((grid_size, grid_size), dtype=np.float64)
    image[body] = 0.70
    image[roof] = 1.00
    image[chimney] = 0.85
    image[door] = 0.18
    image[left_window | right_window] = 0.08
    return _periodic_gaussian_blur_numpy(image, sigma=0.55)


def make_synthetic_butterfly_image(grid_size: int = 28) -> FloatArray:
    """Return a simple ``grid_size x grid_size`` grayscale butterfly image."""
    if grid_size <= 1:
        raise ValueError("grid_size must be at least 2")
    yy, xx = np.mgrid[0:grid_size, 0:grid_size]
    x = (xx + 0.5) / float(grid_size)
    y = (yy + 0.5) / float(grid_size)

    def gaussian(cx: float, cy: float, sx: float, sy: float, amp: float) -> FloatArray:
        return amp * np.exp(-0.5 * (((x - cx) / sx) ** 2 + ((y - cy) / sy) ** 2))

    image = np.zeros((grid_size, grid_size), dtype=np.float64)
    image += gaussian(0.32, 0.38, 0.13, 0.16, 1.00)
    image += gaussian(0.68, 0.38, 0.13, 0.16, 1.00)
    image += gaussian(0.35, 0.67, 0.12, 0.14, 0.85)
    image += gaussian(0.65, 0.67, 0.12, 0.14, 0.85)
    image += gaussian(0.50, 0.53, 0.035, 0.22, 0.95)
    image += gaussian(0.45, 0.22, 0.025, 0.10, 0.35)
    image += gaussian(0.55, 0.22, 0.025, 0.10, 0.35)
    return np.clip(image, 0.0, None)


def normalize_image_to_measure(image: np.ndarray, *, floor: float = 1e-8) -> FloatArray:
    """Flatten a non-negative image into a positive probability vector."""
    arr = np.asarray(image, dtype=np.float64)
    if arr.ndim != 2:
        raise ValueError("image must have shape (H, W)")
    if np.any(~np.isfinite(arr)):
        raise ValueError("image contains non-finite values")
    arr = np.maximum(arr, 0.0) + float(floor)
    total = float(arr.sum())
    if total <= 0.0:
        raise ValueError("image has zero total mass")
    return (arr / total).reshape(-1)


def natural_horizon(config: EulerianImageBridgeConfig) -> float:
    """Return the full bridge time horizon for ``config``."""
    return float(config.horizon_scale) / (
        (2.0 * float(config.alpha) + 1.0) * float(config.grid_size * config.grid_size)
    )


def _periodic_gaussian_blur_numpy(image: np.ndarray, *, sigma: float) -> FloatArray:
    arr = np.asarray(image, dtype=np.float64)
    if sigma <= 0.0:
        return arr.copy()
    radius = max(1, int(math.ceil(3.0 * float(sigma))))
    offsets = np.arange(-radius, radius + 1, dtype=np.float64)
    kernel = np.exp(-0.5 * (offsets / float(sigma)) ** 2)
    kernel /= np.sum(kernel)

    out = np.zeros_like(arr, dtype=np.float64)
    for offset, weight in zip(range(-radius, radius + 1), kernel):
        out += float(weight) * np.roll(arr, shift=offset, axis=-1)
    arr = out
    out = np.zeros_like(arr, dtype=np.float64)
    for offset, weight in zip(range(-radius, radius + 1), kernel):
        out += float(weight) * np.roll(arr, shift=offset, axis=-2)
    return out


def terminal_potential_numpy(
    masses: np.ndarray,
    target_masses: np.ndarray,
    config: EulerianImageBridgeConfig,
) -> FloatArray:
    """Return the multi-scale blurred image discrepancy ``Phi_h(s)``."""
    n = int(config.grid_size)
    num_pixels = n * n
    states = np.asarray(masses, dtype=np.float64)
    target = np.asarray(target_masses, dtype=np.float64).reshape(num_pixels)
    if states.ndim == 1:
        states = states[None, :]
        squeeze = True
    elif states.ndim == 2:
        squeeze = False
    else:
        raise ValueError("masses must have shape (N,) or (B, N)")
    if states.shape[1] != num_pixels:
        raise ValueError("masses have the wrong number of pixels")

    density = states.reshape(-1, n, n) * float(num_pixels)
    target_density = target.reshape(n, n) * float(num_pixels)
    weights = np.asarray(config.blur_weights, dtype=np.float64)
    weights = weights / float(weights.sum())

    phi = np.zeros((states.shape[0],), dtype=np.float64)
    for sigma, weight in zip(config.blur_sigmas, weights):
        diff = density - target_density[None, :, :]
        if sigma > 0.0:
            diff = np.stack(
                [_periodic_gaussian_blur_numpy(frame, sigma=float(sigma)) for frame in diff],
                axis=0,
            )
        phi += float(weight) * np.mean(diff * diff, axis=(1, 2))
    return phi[0] if squeeze else phi


def terminal_preference_numpy(
    masses: np.ndarray,
    target_masses: np.ndarray,
    config: EulerianImageBridgeConfig,
) -> FloatArray:
    """Return ``epsilon + (1 - epsilon) exp(-lambda Phi_h(s))``."""
    phi = terminal_potential_numpy(masses, target_masses, config)
    return config.terminal_floor + (1.0 - config.terminal_floor) * np.exp(
        -float(config.terminal_lambda) * phi
    )


def _gaussian_kernel1d_torch(sigma: float, *, device: torch.device, dtype: torch.dtype) -> Tensor:
    radius = max(1, int(math.ceil(3.0 * float(sigma))))
    offsets = torch.arange(-radius, radius + 1, device=device, dtype=dtype)
    kernel = torch.exp(-0.5 * (offsets / float(sigma)) ** 2)
    return kernel / kernel.sum().clamp_min(torch.finfo(dtype).eps)


def _periodic_gaussian_blur_torch(images: Tensor, *, sigma: float) -> Tensor:
    if sigma <= 0.0:
        return images
    if images.ndim != 4:
        raise ValueError("images must have shape (B, C, H, W)")
    kernel = _gaussian_kernel1d_torch(sigma, device=images.device, dtype=images.dtype)
    radius = int((kernel.numel() - 1) // 2)
    channels = int(images.shape[1])

    kernel_x = kernel.view(1, 1, 1, -1).expand(channels, 1, 1, -1)
    out = F.pad(images, (radius, radius, 0, 0), mode="circular")
    out = F.conv2d(out, kernel_x, groups=channels)

    kernel_y = kernel.view(1, 1, -1, 1).expand(channels, 1, -1, 1)
    out = F.pad(out, (0, 0, radius, radius), mode="circular")
    return F.conv2d(out, kernel_y, groups=channels)


def _target_batch(target_masses: Tensor, batch_size: int) -> Tensor:
    if target_masses.ndim == 1:
        return target_masses[None, :].expand(batch_size, -1)
    if target_masses.ndim == 2 and target_masses.shape[0] == batch_size:
        return target_masses
    raise ValueError("target_masses must have shape (N,) or (B, N)")


def terminal_potential_torch(
    masses: Tensor,
    target_masses: Tensor,
    config: EulerianImageBridgeConfig,
) -> Tensor:
    """Differentiable PyTorch version of :func:`terminal_potential_numpy`."""
    if masses.ndim != 2:
        raise ValueError("masses must have shape (B, N)")
    n = int(config.grid_size)
    num_pixels = n * n
    if masses.shape[1] != num_pixels:
        raise ValueError("masses have the wrong number of pixels")
    target = _target_batch(target_masses.to(device=masses.device, dtype=masses.dtype), masses.shape[0])

    density = masses.reshape(-1, 1, n, n) * float(num_pixels)
    target_density = target.reshape(-1, 1, n, n) * float(num_pixels)
    diff = density - target_density

    weight_sum = float(sum(config.blur_weights))
    phi = torch.zeros((masses.shape[0],), device=masses.device, dtype=masses.dtype)
    for sigma, weight in zip(config.blur_sigmas, config.blur_weights):
        blurred = _periodic_gaussian_blur_torch(diff, sigma=float(sigma))
        phi = phi + float(weight / weight_sum) * torch.mean(blurred.square(), dim=(1, 2, 3))
    return phi


def terminal_preference_torch(
    masses: Tensor,
    target_masses: Tensor,
    config: EulerianImageBridgeConfig,
) -> Tensor:
    """Differentiable PyTorch version of :func:`terminal_preference_numpy`."""
    phi = terminal_potential_torch(masses, target_masses, config)
    return float(config.terminal_floor) + (1.0 - float(config.terminal_floor)) * torch.exp(
        -float(config.terminal_lambda) * phi
    )


class PositiveHeatPotentialCNN(nn.Module):
    """Positive CNN surrogate for ``v_tau(s)=E_s[g_h(S_tau)]``.

    The network output is bounded in ``[terminal_floor, 1]``.  The forward pass
    blends the learned value with the exact terminal score so that
    ``v_0(s) = g_h(s)`` holds exactly.
    """

    def __init__(
        self,
        config: EulerianImageBridgeConfig,
        *,
        hidden_channels: int = 48,
        hidden_dim: int = 128,
        terminal_blend_fraction: float = 0.05,
    ) -> None:
        super().__init__()
        if hidden_channels <= 0 or hidden_dim <= 0:
            raise ValueError("hidden sizes must be positive")
        if terminal_blend_fraction <= 0.0:
            raise ValueError("terminal_blend_fraction must be positive")
        self.config = config
        self.horizon = natural_horizon(config)
        self.terminal_blend_fraction = float(terminal_blend_fraction)
        channels = int(hidden_channels)
        self.conv = nn.Sequential(
            nn.Conv2d(4, channels, kernel_size=3, padding=1, padding_mode="circular"),
            nn.SiLU(),
            nn.Conv2d(channels, channels, kernel_size=3, padding=1, padding_mode="circular"),
            nn.SiLU(),
            nn.Conv2d(channels, channels, kernel_size=3, padding=1, padding_mode="circular"),
            nn.SiLU(),
            nn.Conv2d(channels, channels, kernel_size=3, padding=1, padding_mode="circular"),
            nn.SiLU(),
        )
        self.head = nn.Sequential(
            nn.Flatten(),
            nn.Linear(channels * config.grid_size * config.grid_size, int(hidden_dim)),
            nn.SiLU(),
            nn.Linear(int(hidden_dim), 1),
        )

    def terminal_score(self, masses: Tensor, target_masses: Tensor) -> Tensor:
        return terminal_preference_torch(masses, target_masses, self.config)

    def forward(self, tau: Tensor | float, masses: Tensor, target_masses: Tensor) -> Tensor:
        if masses.ndim != 2:
            raise ValueError("masses must have shape (B, N)")
        batch_size = int(masses.shape[0])
        tau_tensor = torch.as_tensor(tau, dtype=masses.dtype, device=masses.device)
        if tau_tensor.ndim == 0:
            tau_tensor = tau_tensor.repeat(batch_size)
        if tau_tensor.shape != (batch_size,):
            raise ValueError("tau must be scalar or have shape (B,)")
        target = _target_batch(target_masses.to(device=masses.device, dtype=masses.dtype), batch_size)

        n = int(self.config.grid_size)
        num_pixels = n * n
        density = masses.reshape(batch_size, 1, n, n) * float(num_pixels)
        target_density = target.reshape(batch_size, 1, n, n) * float(num_pixels)
        tau_channel = (tau_tensor / max(self.horizon, 1e-12)).view(batch_size, 1, 1, 1)
        tau_channel = tau_channel.expand(batch_size, 1, n, n)
        inputs = torch.cat([density, target_density, density - target_density, tau_channel], dim=1)

        learned = float(self.config.terminal_floor) + (
            1.0 - float(self.config.terminal_floor)
        ) * torch.sigmoid(self.head(self.conv(inputs))).squeeze(1)
        terminal = self.terminal_score(masses, target)
        tau0 = max(self.terminal_blend_fraction * self.horizon, 1e-12)
        blend = (1.0 - torch.exp(-tau_tensor / tau0)).clamp(0.0, 1.0)
        value = (1.0 - blend) * terminal + blend * learned
        return value.clamp_min(float(self.config.terminal_floor))


# ---------------------------------------------------------------------------
# Eulerian edge simulator
# ---------------------------------------------------------------------------


def _edge_color_classes(grid_size: int) -> list[tuple[np.ndarray, np.ndarray]]:
    n = int(grid_size)
    classes: list[list[tuple[int, int]]] = [[], [], [], []]
    for y in range(n):
        for x in range(n):
            tail = y * n + x
            classes[x % 2].append((tail, y * n + ((x + 1) % n)))
            classes[2 + (y % 2)].append((tail, ((y + 1) % n) * n + x))
    result: list[tuple[np.ndarray, np.ndarray]] = []
    for edges in classes:
        tails = np.asarray([edge[0] for edge in edges], dtype=np.int64)
        heads = np.asarray([edge[1] for edge in edges], dtype=np.int64)
        result.append((tails, heads))
    return result


def _validate_state_batch(states: np.ndarray, config: EulerianImageBridgeConfig) -> tuple[FloatArray, bool]:
    arr = np.asarray(states, dtype=np.float64)
    n2 = int(config.grid_size * config.grid_size)
    if arr.ndim == 1:
        arr = arr[None, :]
        squeeze = True
    elif arr.ndim == 2:
        squeeze = False
    else:
        raise ValueError("states must have shape (N,) or (B, N)")
    if arr.shape[1] != n2:
        raise ValueError("state has the wrong number of pixels")
    if np.any(~np.isfinite(arr)):
        raise ValueError("state contains non-finite values")
    arr = np.maximum(arr, float(config.mass_floor))
    arr = arr / arr.sum(axis=1, keepdims=True)
    return arr, squeeze


def _edge_split_step_numpy(
    states: FloatArray,
    dt: float,
    config: EulerianImageBridgeConfig,
    rng: np.random.Generator,
    *,
    potential_value: FloatArray | None = None,
    potential_grad: FloatArray | None = None,
    deterministic: bool = False,
) -> tuple[FloatArray, int, int]:
    if dt < 0.0 or not math.isfinite(dt):
        raise ValueError("dt must be non-negative and finite")
    if dt == 0.0:
        return states.copy(), 0, 0
    n = int(config.grid_size)
    inv_h2 = float(n * n)
    alpha = float(config.alpha)
    tiny = float(config.value_floor)
    out = np.asarray(states, dtype=np.float64).copy()
    clipped = 0
    proposed = 0

    if potential_grad is not None:
        grad = np.asarray(potential_grad, dtype=np.float64)
        if grad.shape != out.shape:
            raise ValueError("potential_grad must have the same shape as states")
        value = np.asarray(potential_value, dtype=np.float64).reshape(-1, 1)
        if value.shape[0] != out.shape[0]:
            raise ValueError("potential_value must have shape (B,)")
        value = np.maximum(value, tiny)
    else:
        grad = None
        value = None

    sqrt_dt = math.sqrt(float(dt))
    for tails, heads in _edge_color_classes(n):
        a = out[:, tails]
        b = out[:, heads]
        denom = a + b
        safe = denom > tiny
        harmonic = np.zeros_like(denom)
        ratio = np.zeros_like(denom)
        harmonic[safe] = (a[safe] * b[safe]) / denom[safe]
        ratio[safe] = (a[safe] - b[safe]) / denom[safe]
        theta = ((2.0 * alpha + 1.0) / alpha) * harmonic
        rate = (2.0 * alpha + 1.0) * inv_h2 * ratio

        if grad is not None and value is not None:
            grad_delta = grad[:, heads] - grad[:, tails]
            rate = rate + 2.0 * theta * inv_h2 * grad_delta / value

        noise = 0.0
        if not deterministic:
            noise = np.sqrt(np.maximum(2.0 * theta * inv_h2, 0.0)) * sqrt_dt
            noise = noise * rng.standard_normal(size=theta.shape)
        d_flux = rate * float(dt) + noise

        pos_clip = d_flux > config.limiter_fraction * a
        neg_clip = d_flux < -config.limiter_fraction * b
        clipped += int(np.count_nonzero(pos_clip) + np.count_nonzero(neg_clip))
        proposed += int(d_flux.size)
        d_flux = np.minimum(d_flux, config.limiter_fraction * a)
        d_flux = np.maximum(d_flux, -config.limiter_fraction * b)

        out[:, tails] -= d_flux
        out[:, heads] += d_flux
        out = np.maximum(out, float(config.mass_floor))
        out /= out.sum(axis=1, keepdims=True)
    return out, clipped, proposed


def _steps_for_time(total_time: float, config: EulerianImageBridgeConfig, num_steps: int | None) -> int:
    if total_time <= 0.0:
        return 0
    if num_steps is not None:
        return max(1, int(num_steps))
    full_horizon = natural_horizon(config)
    return max(1, int(math.ceil(config.num_steps * float(total_time) / full_horizon)))


def simulate_free_rollout(
    initial_state: np.ndarray,
    total_time: float,
    config: EulerianImageBridgeConfig,
    *,
    rng: np.random.Generator | None = None,
    num_steps: int | None = None,
    return_trajectory: bool = False,
    deterministic: bool = False,
) -> EulerianRollout:
    """Simulate the free harmonic-mobility Eulerian image diffusion."""
    rng = np.random.default_rng() if rng is None else rng
    states, squeeze = _validate_state_batch(initial_state, config)
    total_time = float(total_time)
    if total_time < 0.0 or not math.isfinite(total_time):
        raise ValueError("total_time must be non-negative and finite")
    steps = _steps_for_time(total_time, config, num_steps)
    if steps == 0:
        times = np.asarray([0.0], dtype=np.float64)
        traj = states[None, 0 if squeeze else slice(None)].copy()
        final = states[0].copy() if squeeze else states.copy()
        return EulerianRollout(times=times, trajectory=traj, final_state=final, clipping_fraction=0.0)

    dt = total_time / float(steps)
    times = np.linspace(0.0, total_time, steps + 1, dtype=np.float64)
    traj = [states[0].copy() if squeeze else states.copy()] if return_trajectory else []
    clipped = 0
    proposed = 0
    for _ in range(steps):
        states, c_step, p_step = _edge_split_step_numpy(
            states,
            dt,
            config,
            rng,
            deterministic=deterministic,
        )
        clipped += c_step
        proposed += p_step
        if return_trajectory:
            traj.append(states[0].copy() if squeeze else states.copy())

    final = states[0].copy() if squeeze else states.copy()
    if return_trajectory:
        trajectory = np.asarray(traj, dtype=np.float64)
    else:
        trajectory = np.asarray([final], dtype=np.float64)
    return EulerianRollout(
        times=times if return_trajectory else np.asarray([total_time], dtype=np.float64),
        trajectory=trajectory,
        final_state=final,
        clipping_fraction=0.0 if proposed == 0 else float(clipped) / float(proposed),
    )


# ---------------------------------------------------------------------------
# Feynman--Kac regression and conditioned bridge
# ---------------------------------------------------------------------------


def sample_proposal_states(
    num_samples: int,
    house_masses: np.ndarray,
    target_masses: np.ndarray,
    config: EulerianImageBridgeConfig,
    *,
    rng: np.random.Generator | None = None,
    noise_weight: float = 0.05,
) -> FloatArray:
    """Sample states used to train the heat-potential surrogate."""
    if num_samples <= 0:
        raise ValueError("num_samples must be positive")
    rng = np.random.default_rng() if rng is None else rng
    house = np.asarray(house_masses, dtype=np.float64).reshape(-1)
    target = np.asarray(target_masses, dtype=np.float64).reshape(-1)
    if house.shape != target.shape:
        raise ValueError("house_masses and target_masses must have the same shape")

    states = np.empty((int(num_samples), house.shape[0]), dtype=np.float64)
    uniforms = rng.random(int(num_samples))
    mixes = rng.random(int(num_samples))
    for i, selector in enumerate(uniforms):
        if selector < 0.35:
            base = house
        elif selector < 0.70:
            r = mixes[i]
            base = (1.0 - r) * house + r * target
        elif selector < 0.85:
            base = target
        else:
            base = np.full_like(house, 1.0 / float(house.size))
        noise = rng.gamma(shape=1.0, scale=1.0, size=house.shape[0])
        noise = noise / noise.sum()
        states[i] = (1.0 - noise_weight) * base + noise_weight * noise
    states = np.maximum(states, float(config.mass_floor))
    return states / states.sum(axis=1, keepdims=True)


def make_feynman_kac_regression_batch(
    batch_size: int,
    house_masses: np.ndarray,
    target_masses: np.ndarray,
    config: EulerianImageBridgeConfig,
    *,
    rng: np.random.Generator | None = None,
    rollout_steps_per_sample: int = 16,
) -> RegressionBatch:
    """Build one supervised batch ``(tau, s, g_h(S_tau))``."""
    rng = np.random.default_rng() if rng is None else rng
    horizon = natural_horizon(config)
    tau = rng.uniform(0.0, horizon, size=int(batch_size)).astype(np.float64)
    states = sample_proposal_states(batch_size, house_masses, target_masses, config, rng=rng)
    targets = np.empty((int(batch_size),), dtype=np.float64)
    for i in range(int(batch_size)):
        rollout = simulate_free_rollout(
            states[i],
            float(tau[i]),
            config,
            rng=rng,
            num_steps=max(1, int(rollout_steps_per_sample)),
            return_trajectory=False,
        )
        targets[i] = float(terminal_preference_numpy(rollout.final_state, target_masses, config))
    return RegressionBatch(tau=tau, states=states, targets=targets)


def train_heat_potential_surrogate(
    model: PositiveHeatPotentialCNN,
    house_masses: np.ndarray,
    target_masses: np.ndarray,
    *,
    num_batches: int = 100,
    batch_size: int = 64,
    lr: float = 1e-3,
    rollout_steps_per_sample: int = 16,
    log_loss_weight: float = 0.05,
    rng: np.random.Generator | None = None,
    device: str | torch.device | None = None,
) -> dict[str, list[float]]:
    """Train ``model`` on the Feynman--Kac regression target."""
    if num_batches <= 0 or batch_size <= 0:
        raise ValueError("num_batches and batch_size must be positive")
    rng = np.random.default_rng() if rng is None else rng
    resolved_device = torch.device("cpu" if device is None else device)
    model.to(resolved_device)
    model.train()
    optimizer = torch.optim.Adam(model.parameters(), lr=float(lr))
    target_tensor = torch.tensor(target_masses, dtype=torch.float32, device=resolved_device)
    history: dict[str, list[float]] = {"loss": [], "mse": [], "log_mse": []}

    for _ in range(int(num_batches)):
        batch = make_feynman_kac_regression_batch(
            batch_size,
            house_masses,
            target_masses,
            model.config,
            rng=rng,
            rollout_steps_per_sample=rollout_steps_per_sample,
        )
        tau = torch.tensor(batch.tau, dtype=torch.float32, device=resolved_device)
        states = torch.tensor(batch.states, dtype=torch.float32, device=resolved_device)
        y = torch.tensor(batch.targets, dtype=torch.float32, device=resolved_device)
        pred = model(tau, states, target_tensor)
        mse = torch.mean((pred - y).square())
        log_mse = torch.mean((torch.log(pred) - torch.log(y.clamp_min(1e-12))).square())
        loss = mse + float(log_loss_weight) * log_mse

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

        history["loss"].append(float(loss.detach().cpu()))
        history["mse"].append(float(mse.detach().cpu()))
        history["log_mse"].append(float(log_mse.detach().cpu()))
    return history


def _potential_value_and_grad(
    model: PositiveHeatPotentialCNN,
    tau: float,
    state: FloatArray,
    target_masses: FloatArray,
    device: torch.device,
) -> tuple[FloatArray, FloatArray]:
    state_t = torch.tensor(state[None, :], dtype=torch.float32, device=device, requires_grad=True)
    target_t = torch.tensor(target_masses, dtype=torch.float32, device=device)
    tau_t = torch.tensor([float(tau)], dtype=torch.float32, device=device)
    value_t = model(tau_t, state_t, target_t)
    grad_t = torch.autograd.grad(value_t.sum(), state_t, create_graph=False)[0]
    value = value_t.detach().cpu().numpy().astype(np.float64)
    grad = grad_t.detach().cpu().numpy().astype(np.float64)
    return value, grad


def simulate_conditioned_image_bridge(
    model: PositiveHeatPotentialCNN,
    house_masses: np.ndarray,
    target_masses: np.ndarray,
    config: EulerianImageBridgeConfig | None = None,
    *,
    rng: np.random.Generator | None = None,
    num_steps: int | None = None,
    save_every: int = 1,
    deterministic: bool = False,
    device: str | torch.device | None = None,
) -> ConditionedBridgeResult:
    """Simulate the terminally conditioned house-to-butterfly image bridge."""
    cfg = model.config if config is None else config
    if cfg != model.config:
        raise ValueError("config must match model.config")
    if save_every <= 0:
        raise ValueError("save_every must be positive")
    rng = np.random.default_rng() if rng is None else rng
    resolved_device = torch.device("cpu" if device is None else device)
    model.to(resolved_device)
    model.eval()

    state, squeeze = _validate_state_batch(house_masses, cfg)
    if not squeeze:
        raise ValueError("simulate_conditioned_image_bridge expects one initial image")
    target = np.asarray(target_masses, dtype=np.float64).reshape(-1)
    horizon = natural_horizon(cfg)
    steps = int(cfg.num_steps if num_steps is None else num_steps)
    if steps <= 0:
        raise ValueError("num_steps must be positive")
    dt = horizon / float(steps)

    saved_times = [0.0]
    saved_states = [state[0].copy()]
    saved_scores = [float(terminal_preference_numpy(state[0], target, cfg))]
    clipped = 0
    proposed = 0
    with torch.enable_grad():
        for step in range(steps):
            t = float(step) * dt
            tau = max(horizon - t, 0.0)
            value, grad = _potential_value_and_grad(model, tau, state[0], target, resolved_device)
            state, c_step, p_step = _edge_split_step_numpy(
                state,
                dt,
                cfg,
                rng,
                potential_value=value,
                potential_grad=grad,
                deterministic=deterministic,
            )
            clipped += c_step
            proposed += p_step
            if (step + 1) % int(save_every) == 0 or step + 1 == steps:
                saved_times.append(float(step + 1) * dt)
                saved_states.append(state[0].copy())
                saved_scores.append(float(terminal_preference_numpy(state[0], target, cfg)))

    return ConditionedBridgeResult(
        times=np.asarray(saved_times, dtype=np.float64),
        trajectory=np.asarray(saved_states, dtype=np.float64),
        terminal_scores=np.asarray(saved_scores, dtype=np.float64),
        clipping_fraction=0.0 if proposed == 0 else float(clipped) / float(proposed),
    )
